import type { Locale } from '@/lib/i18n/locales'

type Phrase = Record<Locale, string>

export const COACH_PHRASE = {
  steady: {
    ru: 'Держите датчик спокойнее. Ведите медленнее.',
    en: 'Hold the probe steadier. Sweep more slowly.',
    es: 'Sujete el transductor con más calma. Recorra más despacio.',
    fr: 'Tenez la sonde plus stable. Balayez plus lentement.',
    ar: 'ثبّت المجس أكثر. حرّكه ببطء.',
    hi: 'प्रोब को स्थिर रखें। धीरे घुमाएँ।',
    'pt-BR': 'Segure o transdutor mais firme. Varra mais devagar.',
    id: 'Pegang probe lebih tenang. Sapukan lebih pelan.',
    ms: 'Pegang prob dengan lebih stabil. Sapu lebih perlahan.',
    tr: 'Probu daha sabit tutun. Daha yavaş gezdirin.',
    'zh-CN': '探头拿稳一些。扫查再慢一点。',
  },
  soft: {
    ru: 'Кадр нерезкий. Задержите датчик на месте.',
    en: 'The picture is soft. Hold the probe still.',
    es: 'La imagen está borrosa. Detenga el transductor.',
    fr: 'L’image est floue. Immobilisez la sonde.',
    ar: 'الصورة غير حادة. أبقِ المجس ثابتًا.',
    hi: 'चित्र धुंधला है। प्रोब को रोककर रखें।',
    'pt-BR': 'A imagem está turva. Pare o transdutor.',
    id: 'Gambar tidak tajam. Tahan probe di tempat.',
    ms: 'Gambar tidak tajam. Tahan prob di tempat.',
    tr: 'Görüntü bulanık. Probu yerinde tutun.',
    'zh-CN': '图像不清晰。把探头停住。',
  },
  bright: {
    ru: 'Кадр слишком тёмный или яркий. Поправьте усиление на аппарате.',
    en: 'The picture is too dark or too bright. Adjust the gain on the machine.',
    es: 'La imagen está demasiado oscura o clara. Ajuste la ganancia en el equipo.',
    fr: 'L’image est trop sombre ou trop claire. Réglez le gain sur l’appareil.',
    ar: 'الصورة أغمق أو أسطع من اللازم. اضبط الكسب على الجهاز.',
    hi: 'चित्र बहुत गहरा या बहुत चमकीला है। मशीन पर गेन ठीक करें।',
    'pt-BR': 'A imagem está escura ou clara demais. Ajuste o ganho no aparelho.',
    id: 'Gambar terlalu gelap atau terlalu terang. Atur gain di mesin.',
    ms: 'Gambar terlalu gelap atau terlalu terang. Laraskan gain pada mesin.',
    tr: 'Görüntü çok koyu veya çok parlak. Cihazda kazancı düzeltin.',
    'zh-CN': '图像过暗或过亮。在仪器上调整增益。',
  },
  ivc: {
    ru: 'Ослабьте нажатие. Сосуд сжимается.',
    en: 'Press more lightly. The vessel is compressed.',
    es: 'Presione menos. El vaso se comprime.',
    fr: 'Appuyez moins. Le vaisseau est comprimé.',
    ar: 'خفف الضغط. الوعاء ينضغط.',
    hi: 'दबाव कम करें। वाहिका दब रही है।',
    'pt-BR': 'Pressione menos. O vaso está comprimido.',
    id: 'Tekan lebih ringan. Pembuluh tertekan.',
    ms: 'Tekan lebih ringan. Salur darah tertekan.',
    tr: 'Daha hafif bastırın. Damar sıkışıyor.',
    'zh-CN': '减轻按压。血管被压扁了。',
  },
  multi: {
    ru: 'Поверните или наклоните датчик. 30, 45 и 60 градусов — ваш шаг, аппарат угол не измеряет.',
    en: 'Rotate or tilt the probe. 30, 45 and 60 degrees are your step; the machine does not measure the angle.',
    es: 'Gire o incline el transductor. 30, 45 y 60 grados son su paso; el equipo no mide el ángulo.',
    fr: 'Tournez ou inclinez la sonde. 30, 45 et 60 degrés sont votre pas ; l’appareil ne mesure pas l’angle.',
    ar: 'أدر المجس أو أمِله. 30 و45 و60 درجة هي خطوتك؛ الجهاز لا يقيس الزاوية.',
    hi: 'प्रोब को घुमाएँ या झुकाएँ। 30, 45 और 60 डिग्री आपका कदम है; मशीन कोण नहीं मापती।',
    'pt-BR': 'Gire ou incline o transdutor. 30, 45 e 60 graus são o seu passo; o aparelho não mede o ângulo.',
    id: 'Putar atau miringkan probe. 30, 45, dan 60 derajat adalah langkah Anda; mesin tidak mengukur sudut.',
    ms: 'Pusing atau condongkan prob. 30, 45 dan 60 darjah ialah langkah anda; mesin tidak mengukur sudut.',
    tr: 'Probu döndürün veya eğin. 30, 45 ve 60 derece sizin adımınızdır; cihaz açıyı ölçmez.',
    'zh-CN': '转动或倾斜探头。30、45、60度是您自己的步进，仪器不测量角度。',
  },
  sweep: {
    ru: 'Ведите датчик по области и держите картинку на экране.',
    en: 'Sweep the probe across the area and keep the picture on the screen.',
    es: 'Recorra la zona con el transductor y mantenga la imagen en pantalla.',
    fr: 'Balayez la zone avec la sonde et gardez l’image à l’écran.',
    ar: 'حرّك المجس عبر المنطقة وأبقِ الصورة على الشاشة.',
    hi: 'प्रोब को क्षेत्र पर घुमाएँ और चित्र को स्क्रीन पर रखें।',
    'pt-BR': 'Varra a região com o transdutor e mantenha a imagem na tela.',
    id: 'Sapukan probe di area dan jaga gambar tetap di layar.',
    ms: 'Sapu prob merentasi kawasan dan kekalkan gambar pada skrin.',
    tr: 'Probu bölge boyunca gezdirin ve görüntüyü ekranda tutun.',
    'zh-CN': '用探头扫过该区域，让图像留在屏幕上。',
  },
  failReview: {
    ru: 'Заключение сейчас не написалось. Разбор не подключён.',
    en: 'The conclusion could not be written. Review is not connected.',
    es: 'El informe no se escribió. La revisión no está conectada.',
    fr: 'La conclusion n’a pas été écrite. La relecture n’est pas connectée.',
    ar: 'لم يُكتب الاستنتاج. المراجعة غير متصلة.',
    hi: 'निष्कर्ष नहीं लिखा गया। समीक्षा जुड़ी नहीं है।',
    'pt-BR': 'A conclusão não foi escrita. A revisão não está ligada.',
    id: 'Kesimpulan tidak tertulis. Tinjauan tidak terhubung.',
    ms: 'Kesimpulan tidak ditulis. Semakan tidak disambungkan.',
    tr: 'Sonuç yazılamadı. İnceleme bağlı değil.',
    'zh-CN': '结论没有写成。审阅没有接通。',
  },
  failRepeat: {
    ru: 'Заключение сейчас не написалось. Повторите проход.',
    en: 'The conclusion could not be written. Repeat the pass.',
    es: 'El informe no se escribió. Repita el recorrido.',
    fr: 'La conclusion n’a pas été écrite. Recommencez le balayage.',
    ar: 'لم يُكتب الاستنتاج. أعد المرور.',
    hi: 'निष्कर्ष नहीं लिखा गया। पास दोहराएँ।',
    'pt-BR': 'A conclusão não foi escrita. Repita a varredura.',
    id: 'Kesimpulan tidak tertulis. Ulangi sapuan.',
    ms: 'Kesimpulan tidak ditulis. Ulang sapuan.',
    tr: 'Sonuç yazılamadı. Geçişi tekrarlayın.',
    'zh-CN': '结论没有写成。请再扫一遍。',
  },
  rewriteQuality: {
    ru: 'Картинка слишком нечёткая. Повторите проход медленнее.',
    en: 'The picture is too unclear. Sweep again, more slowly.',
    es: 'La imagen está poco clara. Recorra de nuevo, más despacio.',
    fr: 'L’image est trop peu nette. Balayez de nouveau, plus lentement.',
    ar: 'الصورة غير واضحة. أعد المرور ببطء أكبر.',
    hi: 'चित्र बहुत अस्पष्ट है। धीरे दोबारा घुमाएँ।',
    'pt-BR': 'A imagem está pouco nítida. Varra de novo, mais devagar.',
    id: 'Gambar terlalu kabur. Sapu lagi, lebih pelan.',
    ms: 'Gambar terlalu kabur. Sapu semula, lebih perlahan.',
    tr: 'Görüntü çok belirsiz. Daha yavaş yeniden gezdirin.',
    'zh-CN': '图像太不清楚。请再慢一点扫一遍。',
  },
  rewriteArea: {
    ru: 'Сначала выберите область.',
    en: 'Choose the area first.',
    es: 'Primero elija la zona.',
    fr: 'Choisissez d’abord la zone.',
    ar: 'اختر المنطقة أولًا.',
    hi: 'पहले क्षेत्र चुनें।',
    'pt-BR': 'Escolha a região primeiro.',
    id: 'Pilih areanya dulu.',
    ms: 'Pilih kawasan dahulu.',
    tr: 'Önce bölgeyi seçin.',
    'zh-CN': '请先选择区域。',
  },
  rewriteFrames: {
    ru: 'По этим кадрам заключение не собралось. Повторите проход.',
    en: 'These frames did not produce a conclusion. Repeat the pass.',
    es: 'Con estos fotogramas no salió el informe. Repita el recorrido.',
    fr: 'Ces images n’ont pas donné de conclusion. Recommencez le balayage.',
    ar: 'هذه اللقطات لم تعطِ استنتاجًا. أعد المرور.',
    hi: 'इन फ़्रेमों से निष्कर्ष नहीं बना। पास दोहराएँ।',
    'pt-BR': 'Estes quadros não geraram uma conclusão. Repita a varredura.',
    id: 'Bingkai ini tidak menghasilkan kesimpulan. Ulangi sapuan.',
    ms: 'Bingkai ini tidak menghasilkan kesimpulan. Ulang sapuan.',
    tr: 'Bu karelerden sonuç çıkmadı. Geçişi tekrarlayın.',
    'zh-CN': '这些画面没有形成结论。请再扫一遍。',
  },
} satisfies Record<string, Phrase>

export const HEART_LINE: Record<Locale, readonly [string, string, string, string]> = {
  ru: [
    'Парастернальная длинная ось. Покажите сердце вдоль.',
    'Парастернальная короткая ось. Поверните датчик.',
    'Апикальная четырёхкамерная. Наклоните датчик к верхушке.',
    'Апикальная двухкамерная. Поверните ещё и покажите конец расслабления и конец сокращения.',
  ],
  en: [
    'Parasternal long axis. Show the heart along its length.',
    'Parasternal short axis. Rotate the probe.',
    'Apical four-chamber. Tilt the probe toward the apex.',
    'Apical two-chamber. Rotate again and show end-relaxation and end-contraction.',
  ],
  es: [
    'Eje largo paraesternal. Muestre el corazón a lo largo.',
    'Eje corto paraesternal. Gire el transductor.',
    'Cuatro cámaras apical. Incline el transductor hacia el ápex.',
    'Dos cámaras apical. Gire otra vez y muestre el fin de la relajación y el fin de la contracción.',
  ],
  fr: [
    'Grand axe parasternal. Montrez le cœur dans sa longueur.',
    'Petit axe parasternal. Tournez la sonde.',
    'Quatre cavités apical. Inclinez la sonde vers l’apex.',
    'Deux cavités apical. Tournez encore et montrez la fin de relaxation et la fin de contraction.',
  ],
  ar: [
    'المحور الطويل جانب القص. أظهر القلب على طوله.',
    'المحور القصير جانب القص. أدر المجس.',
    'أربع حجرات من القمة. أمِل المجس نحو القمة.',
    'حجرتان من القمة. أدر مرة أخرى وأظهر نهاية الارتخاء ونهاية الانقباض.',
  ],
  hi: [
    'पैरास्टर्नल लंबी अक्ष। हृदय को लंबाई में दिखाएँ।',
    'पैरास्टर्नल छोटी अक्ष। प्रोब घुमाएँ।',
    'एपिकल चार कक्ष। प्रोब को शीर्ष की ओर झुकाएँ।',
    'एपिकल दो कक्ष। फिर घुमाएँ और शिथिलन का अंत तथा संकुचन का अंत दिखाएँ।',
  ],
  'pt-BR': [
    'Eixo longo paraesternal. Mostre o coração no comprimento.',
    'Eixo curto paraesternal. Gire o transdutor.',
    'Quatro câmaras apical. Incline o transdutor para o ápice.',
    'Duas câmaras apical. Gire de novo e mostre o fim do relaxamento e o fim da contração.',
  ],
  id: [
    'Sumbu panjang parasternal. Tunjukkan jantung sepanjang sumbunya.',
    'Sumbu pendek parasternal. Putar probe.',
    'Empat ruang apikal. Miringkan probe ke apeks.',
    'Dua ruang apikal. Putar lagi dan tunjukkan akhir relaksasi serta akhir kontraksi.',
  ],
  ms: [
    'Paksi panjang parasternal. Tunjukkan jantung sepanjang paksi.',
    'Paksi pendek parasternal. Pusing prob.',
    'Empat ruang apeks. Condongkan prob ke apeks.',
    'Dua ruang apeks. Pusing lagi dan tunjukkan hujung relaksasi serta hujung kontraksi.',
  ],
  tr: [
    'Parasternal uzun eksen. Kalbi boyuna gösterin.',
    'Parasternal kısa eksen. Probu döndürün.',
    'Apikal dört boşluk. Probu apekse eğin.',
    'Apikal iki boşluk. Bir kez daha döndürün ve gevşeme sonunu ile kasılma sonunu gösterin.',
  ],
  'zh-CN': [
    '胸骨旁长轴。沿长轴显示心脏。',
    '胸骨旁短轴。转动探头。',
    '心尖四腔。把探头向尖部倾斜。',
    '心尖两腔。再转一次，显示舒张末和收缩末。',
  ],
}
