import type { Locale } from '@/lib/i18n/locales'

type Foreign = Exclude<Locale, 'en' | 'ru'>

export interface GuideChrome {
  close: string
  title: string
  lead: string
  price: string
  looks: string
  cardsTitle: string
  machinesTitle: string
  note: string
  cardName: [string, string, string]
  cardUse: [string, string, string]
  cardExamples: [string, string, string]
  cardPrice: [string, string, string]
  columns: [string, string, string]
  panel: [string, string, string, string, string, string, string]
  between: [string, string, string, string, string, string, string]
}

export const GUIDE_CHROME: Record<Foreign, GuideChrome> = {
  es: {
    close: 'Cerrar',
    title: 'Capturadoras para equipos de ecografía',
    lead: 'La capturadora toma la imagen ya formada en la salida de vídeo y la envía al ordenador por USB. El navegador la ve como una cámara. En esa señal no hay datos crudos del transductor, ni DICOM, ni escala en milímetros.',
    price: 'Los precios de abajo son cifras en dólares de páginas de fabricantes y vendedores. No son el precio de una tienda ni una promesa de que el aparato esté en stock.',
    looks: 'Así se ve',
    cardsTitle: 'Qué capturadoras hay',
    machinesTitle: 'Qué tomar para cada equipo',
    note: 'Antes de comprar, mire el panel trasero del equipo concreto. La etiqueta «4K» de la caja suele referirse a la entrada, no a la imagen que la tarjeta envía al ordenador.',
    cardName: ['HDMI a USB compacta', 'Caja con SDI y HDMI', 'Tarjeta analógica'],
    cardUse: [
      'La primera opción cuando el equipo tiene HDMI. Para el navegador es una cámara ordinaria.',
      'Cuando un equipo grande sale por SDI y no por HDMI. Puede no aparecer en el navegador como cámara ordinaria.',
      'Un equipo antiguo sin HDMI: conector amarillo compuesto o S-Video.',
    ],
    cardExamples: [
      'Una tarjeta económica de la clase UGREEN. Elgato Cam Link 4K. AVerMedia BU113 si el ordenador solo tiene USB-C.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'Una tarjeta con RCA amarillo y S-Video redondo, por ejemplo StarTech SVID2USB232.',
    ],
    cardPrice: [
      'Unos $20 en una tarjeta simple. Cam Link 4K unos $100, captura 1080p60, macOS 13+, el cable HDMI no va incluido. BU113 unos $100, entrada HDMI y salida USB-C, hasta 1080p60. USB 2.0 no le basta.',
      'Unos $179. Hace falta USB4 o Thunderbolt. No es el primer aparato que se compra para SonOpus ultra.',
      'Unos $50. La ficha del SVID2USB232 dice solo Windows. En Mac hay que comprobar que el navegador vea la tarjeta como cámara.',
    ],
    columns: ['Equipo', 'Qué hay en el panel', 'Qué va entre el equipo y el ordenador'],
    panel: [
      'HDMI, a menudo también VGA y S-Video',
      'HDMI y S-Video',
      'HDMI. Essential también figura con VGA',
      'DisplayPort',
      'HDMI o DVI. En carros antiguos puede haber VGA',
      'VGA, S-Video o RCA',
      'No hay salida de vídeo aparte',
    ],
    between: [
      'Cable HDMI y capturadora HDMI a USB. El manual del DC-70 pide 1280×1024 en una pantalla externa, si no la imagen empeora.',
      'La misma capturadora HDMI a USB y un cable HDMI.',
      'Cable HDMI y capturadora HDMI a USB. Si solo hay VGA en vivo, un adaptador activo VGA a HDMI y luego la capturadora.',
      'Adaptador activo DisplayPort a HDMI y luego capturadora HDMI a USB. En algunos EPIQ el adaptador debe estar conectado antes de encender el equipo.',
      'HDMI entra directo en la capturadora. DVI-D usa un cable DVI a HDMI. VGA necesita un adaptador activo.',
      'Adaptador activo VGA a HDMI, o una capturadora USB analógica. En Mac hay que comprobarla en el navegador.',
      'La capturadora no se conecta. Se muestra en el ordenador la pantalla del teléfono o de la tableta donde el programa del transductor ya está abierto.',
    ],
  },
  fr: {
    close: 'Fermer',
    title: 'Cartes de capture pour échographes',
    lead: 'La carte de capture prend l’image déjà formée sur la sortie vidéo et l’envoie à l’ordinateur par USB. Le navigateur la voit comme une caméra. Ce signal n’a pas les données brutes de la sonde, ni de DICOM, ni d’échelle en millimètres.',
    price: 'Les prix ci-dessous sont des montants en dollars tirés de pages de fabricants et de vendeurs. Ce n’est pas un prix de magasin ni une promesse de disponibilité.',
    looks: 'À quoi cela ressemble',
    cardsTitle: 'Quelles cartes existent',
    machinesTitle: 'Quelle carte pour quel appareil',
    note: 'Avant d’acheter, regardez le panneau arrière de l’appareil réel. La mention « 4K » sur la boîte décrit souvent l’entrée, pas l’image que la carte envoie à l’ordinateur.',
    cardName: ['HDMI vers USB compacte', 'Boîtier avec SDI et HDMI', 'Carte analogique'],
    cardUse: [
      'Le premier choix quand l’appareil a une HDMI. Pour le navigateur, c’est une caméra ordinaire.',
      'Quand un grand appareil sort en SDI et non en HDMI. Elle peut ne pas apparaître dans le navigateur comme une caméra ordinaire.',
      'Un ancien appareil sans HDMI : prise composite jaune ou S-Video.',
    ],
    cardExamples: [
      'Une carte peu chère de la classe UGREEN. Elgato Cam Link 4K. AVerMedia BU113 si l’ordinateur n’a que de l’USB-C.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'Une carte avec une prise RCA jaune et une prise S-Video ronde, par exemple StarTech SVID2USB232.',
    ],
    cardPrice: [
      'Environ $20 pour une carte simple. Cam Link 4K environ $100, capture 1080p60, macOS 13+, câble HDMI non inclus. BU113 environ $100, entrée HDMI et sortie USB-C, jusqu’à 1080p60. L’USB 2.0 ne lui suffit pas.',
      'Environ $179. Il faut USB4 ou Thunderbolt. Ce n’est pas le premier appareil à acheter pour SonOpus ultra.',
      'Environ $50. La fiche du SVID2USB232 indique Windows seulement. Sur Mac, vérifier que le navigateur voit la carte comme une caméra.',
    ],
    columns: ['Appareil', 'Ce qu’il y a sur le panneau', 'Ce qui se place entre l’appareil et l’ordinateur'],
    panel: [
      'HDMI, souvent aussi VGA et S-Video',
      'HDMI et S-Video',
      'HDMI. Essential est aussi indiqué avec VGA',
      'DisplayPort',
      'HDMI ou DVI. Les anciens chariots peuvent avoir du VGA',
      'VGA, S-Video ou RCA',
      'Pas de sortie vidéo séparée',
    ],
    between: [
      'Câble HDMI et carte HDMI vers USB. Le manuel du DC-70 demande 1280×1024 sur un écran externe, sinon l’image est moins bonne.',
      'La même carte HDMI vers USB et un câble HDMI.',
      'Câble HDMI et carte HDMI vers USB. Si seul le VGA est actif, un adaptateur actif VGA vers HDMI, puis la carte.',
      'Adaptateur actif DisplayPort vers HDMI, puis carte HDMI vers USB. Sur certains EPIQ, l’adaptateur doit être branché avant d’allumer l’appareil.',
      'L’HDMI va directement dans la carte. Le DVI-D utilise un câble DVI vers HDMI. Le VGA exige un adaptateur actif.',
      'Adaptateur actif VGA vers HDMI, ou une carte USB analogique. Sur Mac, il faut la vérifier dans le navigateur.',
      'La carte de capture ne se branche pas. On montre à l’ordinateur l’écran du téléphone ou de la tablette où le programme de la sonde est déjà ouvert.',
    ],
  },
  ar: {
    close: 'إغلاق',
    title: 'بطاقات التقاط لأجهزة الموجات',
    lead: 'بطاقة الالتقاط تأخذ الصورة الجاهزة من مخرج الفيديو وترسلها إلى الحاسوب عبر USB. يراها المتصفح ككاميرا. في هذه الإشارة لا بيانات خام للمجس ولا DICOM ولا مقياس بالمليمتر.',
    price: 'الأسعار أدناه أرقام بالدولار من صفحات الشركات والبائعين. ليست سعر متجر ولا وعدًا بأن الجهاز متوفر.',
    looks: 'هكذا تبدو',
    cardsTitle: 'ما البطاقات الموجودة',
    machinesTitle: 'ماذا يُؤخذ لكل جهاز',
    note: 'قبل الشراء انظر إلى اللوحة الخلفية للجهاز نفسه. عبارة «4K» على العلبة غالبًا تصف المدخل لا الصورة التي ترسلها البطاقة إلى الحاسوب.',
    cardName: ['HDMI إلى USB مدمجة', 'صندوق مع SDI وHDMI', 'بطاقة تناظرية'],
    cardUse: [
      'الخيار الأول عندما يكون في الجهاز HDMI. يراها المتصفح كاميرا عادية.',
      'عندما يخرج جهاز كبير عبر SDI لا HDMI. قد لا تظهر في المتصفح ككاميرا عادية.',
      'جهاز قديم بلا HDMI: مقبس أصفر مركّب أو S-Video.',
    ],
    cardExamples: [
      'بطاقة رخيصة من فئة UGREEN. Elgato Cam Link 4K. AVerMedia BU113 إذا كان في الحاسوب USB-C فقط.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'بطاقة بمقبس RCA أصفر ومقبس S-Video دائري، مثل StarTech SVID2USB232.',
    ],
    cardPrice: [
      'نحو $20 لبطاقة بسيطة. Cam Link 4K نحو $100، التقاط 1080p60، وmacOS 13+، وكابل HDMI غير مرفق. BU113 نحو $100، مدخل HDMI ومخرج USB-C، حتى 1080p60. USB 2.0 لا يكفيها.',
      'نحو $179. تحتاج USB4 أو Thunderbolt. ليست أول جهاز يُشترى لـ SonOpus ultra.',
      'نحو $50. وصف SVID2USB232 يذكر Windows فقط. على Mac يجب التأكد أن المتصفح يراها كاميرا.',
    ],
    columns: ['الجهاز', 'ما على اللوحة', 'ما يوضع بين الجهاز والحاسوب'],
    panel: [
      'HDMI، وغالبًا VGA وS-Video أيضًا',
      'HDMI وS-Video',
      'HDMI. وEssential مذكور أيضًا مع VGA',
      'DisplayPort',
      'HDMI أو DVI. في العربات القديمة قد يوجد VGA',
      'VGA أو S-Video أو RCA',
      'لا مخرج فيديو منفصل',
    ],
    between: [
      'كابل HDMI وبطاقة HDMI إلى USB. دليل DC-70 يطلب 1280×1024 على شاشة خارجية، وإلا تسوء الصورة.',
      'البطاقة نفسها HDMI إلى USB وكابل HDMI.',
      'كابل HDMI وبطاقة HDMI إلى USB. إذا كان الحيّ VGA فقط، فمحوّل نشط من VGA إلى HDMI ثم البطاقة.',
      'محوّل نشط من DisplayPort إلى HDMI ثم بطاقة HDMI إلى USB. في بعض أجهزة EPIQ يجب وصل المحوّل قبل تشغيل الجهاز.',
      'HDMI يدخل مباشرة إلى البطاقة. DVI-D بكابل DVI إلى HDMI. VGA يحتاج محوّلًا نشطًا.',
      'محوّل نشط من VGA إلى HDMI، أو بطاقة USB تناظرية. على Mac يجب فحصها في المتصفح.',
      'بطاقة الالتقاط لا تُوصل. تُعرض على الحاسوب شاشة الهاتف أو الجهاز اللوحي حيث برنامج المجس مفتوح أصلًا.',
    ],
  },
  hi: {
    close: 'बंद करें',
    title: 'अल्ट्रासाउंड मशीनों के लिए कैप्चर कार्ड',
    lead: 'कैप्चर कार्ड वीडियो आउटपुट की तैयार तस्वीर लेता है और USB से कंप्यूटर को देता है। ब्राउज़र उसे कैमरा मानता है। इस सिग्नल में प्रोब का कच्चा डेटा, DICOM और मिलीमीटर स्केल नहीं होता।',
    price: 'नीचे की कीमतें निर्माता और विक्रेता पृष्ठों के डॉलर आँकड़े हैं। ये दुकान की कीमत नहीं और स्टॉक का वादा नहीं।',
    looks: 'ऐसा दिखता है',
    cardsTitle: 'कौन से कार्ड मिलते हैं',
    machinesTitle: 'किस मशीन के लिए क्या',
    note: 'खरीदने से पहले उसी मशीन का पिछला पैनल देखें। डिब्बे पर «4K» अक्सर इनपुट बताता है, वह चित्र नहीं जो कार्ड कंप्यूटर को भेजता है।',
    cardName: ['छोटा HDMI से USB', 'SDI और HDMI वाला बॉक्स', 'एनालॉग कार्ड'],
    cardUse: [
      'पहला विकल्प जब मशीन में HDMI हो। ब्राउज़र के लिए यह साधारण कैमरा है।',
      'जब बड़ी मशीन HDMI नहीं, SDI देती हो। ब्राउज़र में साधारण कैमरे की तरह न दिखे।',
      'पुरानी मशीन बिना HDMI: पीला कंपोज़िट या S-Video।',
    ],
    cardExamples: [
      'UGREEN वर्ग का सस्ता कार्ड। Elgato Cam Link 4K। AVerMedia BU113 जब कंप्यूटर में केवल USB-C हो।',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'पीले RCA और गोल S-Video वाला कार्ड, जैसे StarTech SVID2USB232।',
    ],
    cardPrice: [
      'साधारण कार्ड लगभग $20। Cam Link 4K लगभग $100, 1080p60 कैप्चर, macOS 13+, HDMI केबल अलग। BU113 लगभग $100, HDMI इन और USB-C आउट, 1080p60 तक। USB 2.0 इसके लिए काफी नहीं।',
      'लगभग $179। USB4 या Thunderbolt चाहिए। SonOpus ultra के लिए यह पहला उपकरण नहीं।',
      'लगभग $50। SVID2USB232 के विवरण में केवल Windows लिखा है। Mac पर ब्राउज़र में जाँचें कि वह कैमरे की तरह दिखे।',
    ],
    columns: ['मशीन', 'पैनल पर क्या है', 'मशीन और कंप्यूटर के बीच क्या लगे'],
    panel: [
      'HDMI, अक्सर VGA और S-Video भी',
      'HDMI और S-Video',
      'HDMI। Essential में VGA भी लिखा है',
      'DisplayPort',
      'HDMI या DVI। पुरानी गाड़ियों में VGA हो सकता है',
      'VGA, S-Video या RCA',
      'अलग वीडियो आउटपुट नहीं',
    ],
    between: [
      'HDMI केबल और HDMI से USB कार्ड। DC-70 की पुस्तिका बाहरी स्क्रीन पर 1280×1024 माँगती है, वरना चित्र खराब होता है।',
      'वही HDMI से USB कार्ड और HDMI केबल।',
      'HDMI केबल और HDMI से USB कार्ड। अगर केवल VGA जीवित है तो सक्रिय VGA से HDMI अडैप्टर, फिर कार्ड।',
      'सक्रिय DisplayPort से HDMI अडैप्टर, फिर HDMI से USB कार्ड। कुछ EPIQ में अडैप्टर मशीन चालू करने से पहले जुड़ा होना चाहिए।',
      'HDMI सीधे कार्ड में। DVI-D के लिए DVI से HDMI केबल। VGA को सक्रिय अडैप्टर चाहिए।',
      'सक्रिय VGA से HDMI अडैप्टर, या एनालॉग USB कार्ड। Mac पर ब्राउज़र में जाँचें।',
      'कैप्चर कार्ड नहीं जुड़ता। कंप्यूटर पर फ़ोन या टैबलेट की स्क्रीन दिखाएँ, जहाँ प्रोब का प्रोग्राम पहले से खुला हो।',
    ],
  },
  'pt-BR': {
    close: 'Fechar',
    title: 'Placas de captura para aparelhos de ultrassom',
    lead: 'A placa de captura pega a imagem já formada na saída de vídeo e a envia ao computador por USB. O navegador a vê como uma câmera. Nesse sinal não há dado bruto do transdutor, nem DICOM, nem escala em milímetros.',
    price: 'Os preços abaixo são valores em dólares de páginas de fabricantes e vendedores. Não são preço de loja nem promessa de estoque.',
    looks: 'Como parece',
    cardsTitle: 'Quais placas existem',
    machinesTitle: 'O que usar em cada aparelho',
    note: 'Antes de comprar, olhe o painel traseiro do aparelho real. O «4K» na caixa muitas vezes descreve a entrada, não a imagem que a placa manda ao computador.',
    cardName: ['HDMI para USB compacta', 'Caixa com SDI e HDMI', 'Placa analógica'],
    cardUse: [
      'A primeira escolha quando o aparelho tem HDMI. Para o navegador é uma câmera comum.',
      'Quando um aparelho grande sai em SDI, não em HDMI. Pode não aparecer no navegador como câmera comum.',
      'Aparelho antigo sem HDMI: plugue amarelo composto ou S-Video.',
    ],
    cardExamples: [
      'Uma placa barata da classe UGREEN. Elgato Cam Link 4K. AVerMedia BU113 quando o computador só tem USB-C.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'Uma placa com RCA amarelo e S-Video redondo, por exemplo StarTech SVID2USB232.',
    ],
    cardPrice: [
      'Cerca de $20 numa placa simples. Cam Link 4K cerca de $100, captura 1080p60, macOS 13+, cabo HDMI não incluso. BU113 cerca de $100, entrada HDMI e saída USB-C, até 1080p60. USB 2.0 não basta.',
      'Cerca de $179. Precisa de USB4 ou Thunderbolt. Não é o primeiro aparelho a comprar para o SonOpus ultra.',
      'Cerca de $50. A ficha do SVID2USB232 diz só Windows. No Mac, confira se o navegador vê a placa como câmera.',
    ],
    columns: ['Aparelho', 'O que há no painel', 'O que fica entre o aparelho e o computador'],
    panel: [
      'HDMI, muitas vezes também VGA e S-Video',
      'HDMI e S-Video',
      'HDMI. O Essential também aparece com VGA',
      'DisplayPort',
      'HDMI ou DVI. Carrinhos antigos podem ter VGA',
      'VGA, S-Video ou RCA',
      'Não há saída de vídeo separada',
    ],
    between: [
      'Cabo HDMI e placa HDMI para USB. O manual do DC-70 pede 1280×1024 numa tela externa, senão a imagem piora.',
      'A mesma placa HDMI para USB e um cabo HDMI.',
      'Cabo HDMI e placa HDMI para USB. Se só o VGA estiver ativo, um adaptador ativo VGA para HDMI e depois a placa.',
      'Adaptador ativo DisplayPort para HDMI e depois placa HDMI para USB. Em alguns EPIQ o adaptador deve estar ligado antes de ligar o aparelho.',
      'HDMI entra direto na placa. DVI-D usa cabo DVI para HDMI. VGA precisa de adaptador ativo.',
      'Adaptador ativo VGA para HDMI, ou uma placa USB analógica. No Mac, confira no navegador.',
      'A placa de captura não se conecta. Mostre no computador a tela do telefone ou do tablet onde o programa do transdutor já está aberto.',
    ],
  },
  id: {
    close: 'Tutup',
    title: 'Kartu tangkap untuk mesin USG',
    lead: 'Kartu tangkap mengambil gambar yang sudah jadi dari keluaran video dan mengirimnya ke komputer lewat USB. Peramban melihatnya sebagai kamera. Sinyal ini tidak berisi data mentah probe, DICOM, atau skala milimeter.',
    price: 'Harga di bawah adalah angka dolar dari halaman produsen dan penjual. Bukan harga toko dan bukan janji bahwa barang ada.',
    looks: 'Begini bentuknya',
    cardsTitle: 'Kartu yang ada',
    machinesTitle: 'Apa yang dipakai untuk mesin mana',
    note: 'Sebelum membeli, lihat panel belakang mesin yang sebenarnya. Tulisan «4K» di kotak sering menyebut masukan, bukan gambar yang kartu kirim ke komputer.',
    cardName: ['HDMI ke USB yang ringkas', 'Kotak dengan SDI dan HDMI', 'Kartu analog'],
    cardUse: [
      'Pilihan pertama bila mesin punya HDMI. Bagi peramban ini kamera biasa.',
      'Bila mesin besar keluar lewat SDI, bukan HDMI. Mungkin tidak muncul di peramban sebagai kamera biasa.',
      'Mesin lama tanpa HDMI: colokan komposit kuning atau S-Video.',
    ],
    cardExamples: [
      'Kartu murah kelas UGREEN. Elgato Cam Link 4K. AVerMedia BU113 jika komputer hanya punya USB-C.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'Kartu dengan RCA kuning dan S-Video bundar, misalnya StarTech SVID2USB232.',
    ],
    cardPrice: [
      'Sekitar $20 untuk kartu sederhana. Cam Link 4K sekitar $100, tangkapan 1080p60, macOS 13+, kabel HDMI tidak termasuk. BU113 sekitar $100, masukan HDMI dan keluaran USB-C, hingga 1080p60. USB 2.0 tidak cukup.',
      'Sekitar $179. Perlu USB4 atau Thunderbolt. Ini bukan perangkat pertama untuk SonOpus ultra.',
      'Sekitar $50. Keterangan SVID2USB232 hanya menyebut Windows. Di Mac, pastikan peramban melihatnya sebagai kamera.',
    ],
    columns: ['Mesin', 'Apa yang ada di panel', 'Apa yang diletakkan antara mesin dan komputer'],
    panel: [
      'HDMI, sering juga VGA dan S-Video',
      'HDMI dan S-Video',
      'HDMI. Essential juga tercantum dengan VGA',
      'DisplayPort',
      'HDMI atau DVI. Troli lama bisa punya VGA',
      'VGA, S-Video, atau RCA',
      'Tidak ada keluaran video terpisah',
    ],
    between: [
      'Kabel HDMI dan kartu HDMI ke USB. Panduan DC-70 meminta 1280×1024 pada layar luar, jika tidak gambar lebih buruk.',
      'Kartu HDMI ke USB yang sama dan kabel HDMI.',
      'Kabel HDMI dan kartu HDMI ke USB. Jika yang hidup hanya VGA, adaptor aktif VGA ke HDMI, lalu kartu.',
      'Adaptor aktif DisplayPort ke HDMI, lalu kartu HDMI ke USB. Pada sebagian EPIQ adaptor harus terpasang sebelum mesin dinyalakan.',
      'HDMI langsung ke kartu. DVI-D memakai kabel DVI ke HDMI. VGA perlu adaptor aktif.',
      'Adaptor aktif VGA ke HDMI, atau kartu USB analog. Di Mac, periksa di peramban.',
      'Kartu tangkap tidak disambungkan. Tampilkan di komputer layar ponsel atau tablet tempat program probe sudah terbuka.',
    ],
  },
  ms: {
    close: 'Tutup',
    title: 'Kad tangkap untuk mesin ultrasound',
    lead: 'Kad tangkap mengambil gambar yang sudah siap dari keluaran video dan menghantarnya ke komputer melalui USB. Pelayar melihatnya sebagai kamera. Isyarat ini tiada data mentah prob, tiada DICOM, dan tiada skala milimeter.',
    price: 'Harga di bawah ialah angka dolar dari halaman pengeluar dan penjual. Bukan harga kedai dan bukan janji stok.',
    looks: 'Begini rupanya',
    cardsTitle: 'Kad yang ada',
    machinesTitle: 'Apa untuk mesin yang mana',
    note: 'Sebelum membeli, lihat panel belakang mesin sebenar. Label «4K» pada kotak sering merujuk masukan, bukan gambar yang kad hantar ke komputer.',
    cardName: ['HDMI ke USB yang padat', 'Kotak dengan SDI dan HDMI', 'Kad analog'],
    cardUse: [
      'Pilihan pertama apabila mesin ada HDMI. Bagi pelayar ini kamera biasa.',
      'Apabila mesin besar keluar melalui SDI, bukan HDMI. Mungkin tidak muncul dalam pelayar sebagai kamera biasa.',
      'Mesin lama tanpa HDMI: palam komposit kuning atau S-Video.',
    ],
    cardExamples: [
      'Kad murah kelas UGREEN. Elgato Cam Link 4K. AVerMedia BU113 jika komputer hanya ada USB-C.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'Kad dengan RCA kuning dan S-Video bulat, contohnya StarTech SVID2USB232.',
    ],
    cardPrice: [
      'Kira-kira $20 untuk kad mudah. Cam Link 4K kira-kira $100, tangkapan 1080p60, macOS 13+, kabel HDMI tidak disertakan. BU113 kira-kira $100, masukan HDMI dan keluaran USB-C, sehingga 1080p60. USB 2.0 tidak memadai.',
      'Kira-kira $179. Perlukan USB4 atau Thunderbolt. Ini bukan peranti pertama untuk SonOpus ultra.',
      'Kira-kira $50. Keterangan SVID2USB232 menyebut Windows sahaja. Pada Mac, pastikan pelayar melihatnya sebagai kamera.',
    ],
    columns: ['Mesin', 'Apa pada panel', 'Apa antara mesin dan komputer'],
    panel: [
      'HDMI, kerap juga VGA dan S-Video',
      'HDMI dan S-Video',
      'HDMI. Essential juga disenaraikan dengan VGA',
      'DisplayPort',
      'HDMI atau DVI. Troli lama mungkin ada VGA',
      'VGA, S-Video atau RCA',
      'Tiada keluaran video berasingan',
    ],
    between: [
      'Kabel HDMI dan kad HDMI ke USB. Manual DC-70 meminta 1280×1024 pada skrin luar, jika tidak gambar lebih teruk.',
      'Kad HDMI ke USB yang sama dan kabel HDMI.',
      'Kabel HDMI dan kad HDMI ke USB. Jika hanya VGA yang hidup, penyesuai aktif VGA ke HDMI, kemudian kad.',
      'Penyesuai aktif DisplayPort ke HDMI, kemudian kad HDMI ke USB. Pada sesetengah EPIQ penyesuai mesti dipasang sebelum mesin dihidupkan.',
      'HDMI terus ke kad. DVI-D menggunakan kabel DVI ke HDMI. VGA perlukan penyesuai aktif.',
      'Penyesuai aktif VGA ke HDMI, atau kad USB analog. Pada Mac, semak dalam pelayar.',
      'Kad tangkap tidak disambungkan. Tunjukkan pada komputer skrin telefon atau tablet tempat program prob sudah terbuka.',
    ],
  },
  tr: {
    close: 'Kapat',
    title: 'Ultrason cihazları için yakalama kartları',
    lead: 'Yakalama kartı, video çıkışındaki hazır görüntüyü alır ve USB ile bilgisayara verir. Tarayıcı onu kamera olarak görür. Bu sinyalde probun ham verisi, DICOM ve milimetre ölçeği yoktur.',
    price: 'Aşağıdaki fiyatlar üretici ve satıcı sayfalarındaki dolar rakamlarıdır. Mağaza fiyatı değildir ve stok sözü değildir.',
    looks: 'Böyle görünür',
    cardsTitle: 'Hangi kartlar olur',
    machinesTitle: 'Hangi cihaz için ne',
    note: 'Satın almadan önce o cihazın arka paneline bakın. Kutudaki «4K» yazısı çoğu zaman girişi anlatır, kartın bilgisayara gönderdiği görüntüyü değil.',
    cardName: ['Kompakt HDMI’den USB’ye', 'SDI ve HDMI’li kutu', 'Analog kart'],
    cardUse: [
      'Cihazda HDMI varsa ilk seçim. Tarayıcı için sıradan bir kameradır.',
      'Büyük cihaz HDMI değil SDI veriyorsa. Tarayıcıda sıradan kamera olarak görünmeyebilir.',
      'HDMI’si olmayan eski cihaz: sarı kompozit veya S-Video.',
    ],
    cardExamples: [
      'UGREEN sınıfında ucuz bir kart. Elgato Cam Link 4K. Bilgisayarda yalnız USB-C varsa AVerMedia BU113.',
      'Blackmagic UltraStudio Express Recorder 3G.',
      'Sarı RCA ve yuvarlak S-Video soketli kart, örneğin StarTech SVID2USB232.',
    ],
    cardPrice: [
      'Basit kart yaklaşık $20. Cam Link 4K yaklaşık $100, 1080p60 yakalama, macOS 13+, HDMI kablosu dahil değil. BU113 yaklaşık $100, HDMI giriş ve USB-C çıkış, 1080p60’a kadar. USB 2.0 yetmez.',
      'Yaklaşık $179. USB4 veya Thunderbolt gerekir. SonOpus ultra için alınacak ilk cihaz bu değildir.',
      'Yaklaşık $50. SVID2USB232 açıklaması yalnız Windows der. Mac’te tarayıcının kartı kamera olarak gördüğünü kontrol edin.',
    ],
    columns: ['Cihaz', 'Panelde ne var', 'Cihaz ile bilgisayar arasına ne konur'],
    panel: [
      'HDMI, çoğu zaman VGA ve S-Video da',
      'HDMI ve S-Video',
      'HDMI. Essential için VGA da yazılır',
      'DisplayPort',
      'HDMI veya DVI. Eski arabalarda VGA olabilir',
      'VGA, S-Video veya RCA',
      'Ayrı video çıkışı yok',
    ],
    between: [
      'HDMI kablosu ve HDMI’den USB’ye kart. DC-70 kılavuzu dış ekranda 1280×1024 ister, yoksa görüntü bozulur.',
      'Aynı HDMI’den USB’ye kart ve HDMI kablosu.',
      'HDMI kablosu ve HDMI’den USB’ye kart. Yalnız VGA canlıysa etkin VGA’dan HDMI’ye dönüştürücü, sonra kart.',
      'Etkin DisplayPort’tan HDMI’ye dönüştürücü, sonra HDMI’den USB’ye kart. Bazı EPIQ cihazlarında dönüştürücü, cihaz açılmadan önce takılı olmalıdır.',
      'HDMI doğrudan karta girer. DVI-D, DVI’den HDMI’ye kablo kullanır. VGA etkin dönüştürücü ister.',
      'Etkin VGA’dan HDMI’ye dönüştürücü ya da analog USB kart. Mac’te tarayıcıda kontrol edin.',
      'Yakalama kartı bağlanmaz. Prob programının açık olduğu telefon veya tablet ekranı bilgisayarda gösterilir.',
    ],
  },
  'zh-CN': {
    close: '关闭',
    title: '超声仪用的采集卡',
    lead: '采集卡从视频输出口取得已经形成的图像，经 USB 送入电脑。浏览器把它当作摄像头。这路信号里没有探头原始数据，没有 DICOM，也没有毫米刻度。',
    price: '下面的价格是厂商和销售页面上的美元数字。不是商店售价，也不保证有货。',
    looks: '外观',
    cardsTitle: '常见的卡',
    machinesTitle: '哪种仪器配什么',
    note: '购买前先看这台仪器的后面板。盒子上的「4K」常常指输入，不是卡送给电脑的那路图像。',
    cardName: ['小型 HDMI 转 USB', '带 SDI 和 HDMI 的盒子', '模拟采集卡'],
    cardUse: [
      '仪器有 HDMI 时的第一选择。对浏览器来说就是普通摄像头。',
      '大型仪器输出的是 SDI 而不是 HDMI。它可能不会作为普通摄像头出现在浏览器里。',
      '没有 HDMI 的旧仪器：黄色复合接口或 S-Video。',
    ],
    cardExamples: [
      'UGREEN 这一类的便宜采集卡。Elgato Cam Link 4K。电脑只有 USB-C 时用 AVerMedia BU113。',
      'Blackmagic UltraStudio Express Recorder 3G。',
      '带黄色 RCA 和圆形 S-Video 的卡，例如 StarTech SVID2USB232。',
    ],
    cardPrice: [
      '简单的卡大约 $20。Cam Link 4K 大约 $100，采集 1080p60，macOS 13 及以上，不含 HDMI 线。BU113 大约 $100，HDMI 输入、USB-C 输出，最高 1080p60。USB 2.0 不够。',
      '大约 $179。需要 USB4 或 Thunderbolt。这不是给 SonOpus ultra 买的第一件设备。',
      '大约 $50。SVID2USB232 的说明只写了 Windows。在 Mac 上要确认浏览器能把它当成摄像头。',
    ],
    columns: ['仪器', '面板上有什么', '仪器和电脑之间接什么'],
    panel: [
      'HDMI，常常还有 VGA 和 S-Video',
      'HDMI 和 S-Video',
      'HDMI。Essential 的说明里也有 VGA',
      'DisplayPort',
      'HDMI 或 DVI。旧推车上可能有 VGA',
      'VGA、S-Video 或 RCA',
      '没有单独的视频输出',
    ],
    between: [
      'HDMI 线和 HDMI 转 USB 采集卡。DC-70 手册要求外接显示器为 1280×1024，否则图像更差。',
      '同一块 HDMI 转 USB 采集卡和 HDMI 线。',
      'HDMI 线和 HDMI 转 USB 采集卡。如果只有 VGA 有信号，先用有源 VGA 转 HDMI，再接采集卡。',
      '有源 DisplayPort 转 HDMI，再接 HDMI 转 USB 采集卡。部分 EPIQ 必须在开机前接好转换器。',
      'HDMI 直接进采集卡。DVI-D 用 DVI 转 HDMI 线。VGA 需要有源转换器。',
      '有源 VGA 转 HDMI，或模拟 USB 采集卡。在 Mac 上要在浏览器里确认能看见它。',
      '采集卡接不上。把已经打开探头程序的手机或平板屏幕显示到电脑上。',
    ],
  },
}
