import type { ScreenCopy } from '@/lib/ultra/screen-copy'
import type { Locale } from '@/lib/i18n/locales'

type Foreign = Exclude<Locale, 'en' | 'ru'>

function pack(copy: ScreenCopy): ScreenCopy {
  return copy
}

const shared = {
  brand: 'SonOpus ultra',
  wifi: 'Wi‑Fi',
}

export const INTL: Record<Foreign, ScreenCopy> = {
  es: pack({
    ...shared,
    lead: 'Conecte el transductor, elija la zona y recorra.',
    steps: ['Conectar', 'Zona', 'Recorrido', 'Resultado'],
    intro: 'Dos caminos. Directo: la salida de vídeo del equipo, por una capturadora, al USB del ordenador. O el transductor y su programa en una tableta, un teléfono o un ordenador, por cable o Wi‑Fi.',
    howConnect: 'Cómo conectar',
    direct: 'Directo al equipo',
    probeProgram: 'Transductor y programa',
    where: 'Dónde está el programa',
    machineSteps: [
      'Equipo de ecografía, salida de vídeo → cable → capturadora HDMI a USB → USB del ordenador. La toma HDMI del ordenador no recibe la imagen.',
      'Casi siempre basta un cable HDMI. DVI usa un cable DVI a HDMI. DisplayPort y VGA solo con un adaptador activo a HDMI.',
      'La capturadora toma la imagen del equipo y la envía al ordenador. No es un adaptador que manda la pantalla del ordenador a un monitor.',
      'Pulse «Abrir la imagen del equipo» y permita la cámara. Si hay varios dispositivos, elija el que muestra el equipo y luego «Siguiente».',
    ],
    openMachine: 'Abrir la imagen del equipo',
    cards: 'Capturadoras para equipos',
    machineCamera: 'Dónde se ve el equipo',
    onComputer: 'En este ordenador',
    onPocket: 'En una tableta o un teléfono',
    howLink: 'Cómo se une el transductor al programa',
    cable: 'Cable',
    practice: 'Sin equipo, para practicar',
    practiceNote: 'Imagen de práctica. No entra en la historia del paciente.',
    camera: 'Qué transductor',
    next: 'Siguiente',
    guide: {
      computer: {
        cable: [
          'Conecte el transductor por cable a este ordenador y abra el programa del equipo.',
          'Pulse «Abrir la imagen». Permítalo cuando el navegador lo pida.',
          'Si hay varios dispositivos, elija el transductor.',
          'Cuando aparezca la imagen, pulse «Siguiente».',
        ],
        wifi: [
          'Una el transductor al programa de este ordenador por Wi‑Fi y abra la imagen en vivo.',
          'Pulse «Mostrar la ventana del programa».',
          'En la pregunta del navegador, elija la ventana del programa del equipo.',
          'Cuando aparezca la imagen, pulse «Siguiente».',
        ],
      },
      pocket: {
        cable: [
          'Conecte el transductor por cable a la tableta o al teléfono. La imagen en vivo debe estar en esa pantalla.',
          'Muestre esa pantalla en el ordenador, por cable o por compartir pantalla.',
          'Pulse «Mostrar la pantalla» y elija la pantalla de la tableta o del teléfono.',
          'Cuando aparezca la imagen, pulse «Siguiente».',
        ],
        wifi: [
          'Una el transductor al programa de la tableta o del teléfono por Wi‑Fi. La imagen en vivo debe estar en esa pantalla.',
          'Muestre esa pantalla en el ordenador, por cable o por compartir pantalla por Wi‑Fi.',
          'Pulse «Mostrar la pantalla» y elija la pantalla de la tableta o del teléfono.',
          'Cuando aparezca la imagen, pulse «Siguiente».',
        ],
      },
    },
    practiceSteps: [
      'No hace falta transductor. Es una imagen de práctica.',
      'Pulse «Mostrar la imagen de práctica».',
      'No entra en la historia del paciente.',
      'Cuando aparezca la imagen, pulse «Siguiente».',
    ],
    openCable: 'Abrir la imagen',
    openWindow: 'Mostrar la ventana del programa',
    openScreen: 'Mostrar la pantalla',
    openPractice: 'Mostrar la imagen de práctica',
    pictureReady: 'La imagen está. Ya puede elegir la zona.',
    mirror: 'Si esta página aparece dentro de la imagen, pulse «Abrir de nuevo» y elija la ventana del programa del equipo. Esta ventana no debe compartirse.',
    again: 'Abrir de nuevo',
    areaLead: 'La imagen ya está abierta. Elija el órgano y pulse «Empezar». Durante el recorrido, un aviso queda sobre la imagen.',
    areaShared: 'La ventana del programa está conectada. Mírela allí. Aquí elija el órgano y pulse «Empezar».',
    speak: 'Leer la instrucción',
    speakOn: 'La instrucción se lee',
    speakHow: 'Para oír esta línea, pulse «Leer la instrucción».',
    speakLead: '«Leer la instrucción» dice la línea que aparecerá durante el recorrido. Esto no enciende el micrófono.',
    micLead: 'El micrófono graba el dictado, incluidos los tamaños que usted dice. Antes del informe se pasa al lenguaje de la ecografía. La orden «snapshot» guarda el fotograma.',
    polishing: 'Paso el dictado al lenguaje de la ecografía…',
    dictation: 'Dictado',
    dictationHint: 'Estas palabras van al informe junto con los fotogramas. El sonido se queda en esta pestaña.',
    noAudio: 'En este recorrido no se grabó la voz.',
    snapshotHint: 'Pulse «Encender el micrófono». Permítalo cuando el navegador lo pida. Luego diga: snapshot. O pulse «Guardar este fotograma».',
    listen: 'Encender el micrófono',
    listenOn: 'Escuchando. El dictado se graba. Diga: snapshot.',
    listenNoCommand: 'El dictado se graba. Este navegador no oye «snapshot».',
    listenAsk: 'El navegador pide el micrófono. Permítalo.',
    listenDenied: 'El micrófono está bloqueado. Permítalo en el navegador o pulse «Guardar este fotograma».',
    listenNone: 'Este navegador no oye la orden. Pulse «Guardar este fotograma».',
    keepFrame: 'Guardar este fotograma',
    kept: 'Fotograma guardado.',
    pinned: 'Fotogramas guardados',
    scrub: 'Bucle',
    watchProgram: 'Mire la ventana del programa del equipo. Aquí no repetimos la imagen, para que la página no se capture a sí misma.',
    own: 'Otra zona',
    ownPlaceholder: 'Si no está en la lista',
    start: 'Empezar',
    stop: 'Detener',
    live: 'Imagen del equipo',
    writing: 'Elijo fotogramas y escribo el informe…',
    empty: 'El recorrido está vacío. Vuelva y pase el transductor.',
    reset: 'Reiniciar',
    cine: 'El recorrido',
    series: 'Fotogramas representativos',
    conclusion: 'Borrador del informe',
    protocol: 'Protocolo del ecografista',
    seen: 'Qué se ve',
    none: 'No hay una redacción aparte. Eso no significa que todo sea normal.',
    draft: 'Borrador',
    accepted: 'Aceptado',
    rejected: 'Rechazado',
    accept: 'Aceptar',
    reject: 'Rechazar',
    wording: 'Redacción',
    disclaimer: 'Hasta que acepte la redacción, esto no es un informe.',
  }),
  fr: pack({
    ...shared,
    lead: 'Branchez la sonde, choisissez la zone, balayez.',
    steps: ['Brancher', 'Zone', 'Balayage', 'Résultat'],
    intro: 'Deux voies. Directe : la sortie vidéo de l’appareil, par une carte de capture, vers l’USB de l’ordinateur. Ou la sonde et son programme sur une tablette, un téléphone ou un ordinateur, par câble ou Wi‑Fi.',
    howConnect: 'Comment brancher',
    direct: 'Directement sur l’appareil',
    probeProgram: 'Sonde et programme',
    where: 'Où est le programme',
    machineSteps: [
      'Échographe, sortie vidéo → câble → carte de capture HDMI vers USB → USB de l’ordinateur. La prise HDMI de l’ordinateur ne reçoit pas l’image.',
      'Un câble HDMI suffit le plus souvent. Le DVI utilise un câble DVI vers HDMI. DisplayPort et VGA exigent un adaptateur actif vers HDMI.',
      'La carte de capture prend l’image de l’appareil et l’envoie à l’ordinateur. Ce n’est pas un adaptateur qui envoie l’écran de l’ordinateur vers un moniteur.',
      'Appuyez sur « Ouvrir l’image de l’appareil » et autorisez la caméra. S’il y a plusieurs appareils, choisissez celui qui montre l’échographe, puis « Suivant ».',
    ],
    openMachine: 'Ouvrir l’image de l’appareil',
    cards: 'Cartes pour les appareils',
    machineCamera: 'Où l’appareil est visible',
    onComputer: 'Sur cet ordinateur',
    onPocket: 'Sur une tablette ou un téléphone',
    howLink: 'Comment la sonde rejoint le programme',
    cable: 'Câble',
    practice: 'Sans appareil, pour s’exercer',
    practiceNote: 'Image d’exercice. Elle n’entre pas dans le dossier du patient.',
    camera: 'Quelle sonde',
    next: 'Suivant',
    guide: {
      computer: {
        cable: [
          'Branchez la sonde par câble à cet ordinateur et ouvrez le programme de l’appareil.',
          'Appuyez sur « Ouvrir l’image ». Autorisez-la quand le navigateur le demande.',
          'S’il y a plusieurs appareils, choisissez la sonde.',
          'Quand l’image apparaît, appuyez sur « Suivant ».',
        ],
        wifi: [
          'Reliez la sonde au programme de cet ordinateur en Wi‑Fi et ouvrez l’image en direct.',
          'Appuyez sur « Montrer la fenêtre du programme ».',
          'Dans la demande du navigateur, choisissez la fenêtre du programme de l’appareil.',
          'Quand l’image apparaît, appuyez sur « Suivant ».',
        ],
      },
      pocket: {
        cable: [
          'Branchez la sonde par câble à la tablette ou au téléphone. L’image en direct doit être sur cet écran.',
          'Montrez cet écran sur l’ordinateur, par câble ou par partage d’écran.',
          'Appuyez sur « Montrer l’écran » et choisissez l’écran de la tablette ou du téléphone.',
          'Quand l’image apparaît, appuyez sur « Suivant ».',
        ],
        wifi: [
          'Reliez la sonde au programme de la tablette ou du téléphone en Wi‑Fi. L’image en direct doit être sur cet écran.',
          'Montrez cet écran sur l’ordinateur, par câble ou par partage d’écran en Wi‑Fi.',
          'Appuyez sur « Montrer l’écran » et choisissez l’écran de la tablette ou du téléphone.',
          'Quand l’image apparaît, appuyez sur « Suivant ».',
        ],
      },
    },
    practiceSteps: [
      'Aucune sonde n’est nécessaire. C’est une image d’exercice.',
      'Appuyez sur « Montrer l’image d’exercice ».',
      'Elle n’entre pas dans le dossier du patient.',
      'Quand l’image apparaît, appuyez sur « Suivant ».',
    ],
    openCable: 'Ouvrir l’image',
    openWindow: 'Montrer la fenêtre du programme',
    openScreen: 'Montrer l’écran',
    openPractice: 'Montrer l’image d’exercice',
    pictureReady: 'L’image est là. Vous pouvez choisir la zone.',
    mirror: 'Si cette page apparaît dans l’image, appuyez sur « Ouvrir encore » et choisissez la fenêtre du programme de l’appareil. Cette fenêtre ne doit pas être partagée.',
    again: 'Ouvrir encore',
    areaLead: 'L’image est déjà ouverte. Choisissez l’organe et appuyez sur « Commencer ». Pendant le balayage, une indication reste au-dessus de l’image.',
    areaShared: 'La fenêtre du programme est connectée. Regardez-la là. Ici, choisissez l’organe et appuyez sur « Commencer ».',
    speak: 'Lire l’indication',
    speakOn: 'L’indication est lue',
    speakHow: 'Pour entendre cette ligne, appuyez sur « Lire l’indication ».',
    speakLead: '« Lire l’indication » dit la ligne qui apparaîtra pendant le balayage. Cela n’allume pas le microphone.',
    micLead: 'Le microphone enregistre la dictée, y compris les tailles que vous dites. Avant la conclusion, elle est mise en langage d’échographie. L’ordre « snapshot » garde l’image.',
    polishing: 'Je mets la dictée en langage d’échographie…',
    dictation: 'Dictée',
    dictationHint: 'Ces mots vont dans la conclusion avec les images. Le son reste dans cet onglet.',
    noAudio: 'Aucune voix n’a été enregistrée sur ce passage.',
    snapshotHint: 'Appuyez sur « Allumer le microphone ». Autorisez-le quand le navigateur le demande. Puis dites : snapshot. Ou appuyez sur « Garder cette image ».',
    listen: 'Allumer le microphone',
    listenOn: 'J’écoute. La dictée s’enregistre. Dites : snapshot.',
    listenNoCommand: 'La dictée s’enregistre. Ce navigateur n’entend pas « snapshot ».',
    listenAsk: 'Le navigateur demande le microphone. Autorisez-le.',
    listenDenied: 'Le microphone est bloqué. Autorisez-le dans le navigateur, ou appuyez sur « Garder cette image ».',
    listenNone: 'Ce navigateur n’entend pas l’ordre. Appuyez sur « Garder cette image ».',
    keepFrame: 'Garder cette image',
    kept: 'Image gardée.',
    pinned: 'Images gardées',
    scrub: 'Boucle',
    watchProgram: 'Regardez la fenêtre du programme de l’appareil. L’image n’est pas répétée ici, pour que la page ne se capture pas elle-même.',
    own: 'Autre zone',
    ownPlaceholder: 'Si elle n’est pas dans la liste',
    start: 'Commencer',
    stop: 'Arrêter',
    live: 'Image de l’appareil',
    writing: 'Je choisis les images et j’écris la conclusion…',
    empty: 'Le passage est vide. Revenez et balayez avec la sonde.',
    reset: 'Remise à zéro',
    cine: 'Le passage',
    series: 'Images représentatives',
    conclusion: 'Brouillon de conclusion',
    protocol: 'Protocole de l’échographiste',
    seen: 'Ce qui est vu',
    none: 'Il n’y a pas de formulation séparée. Cela ne veut pas dire que tout est normal.',
    draft: 'Brouillon',
    accepted: 'Accepté',
    rejected: 'Refusé',
    accept: 'Accepter',
    reject: 'Refuser',
    wording: 'Formulation',
    disclaimer: 'Tant que vous n’avez pas accepté la formulation, ce n’est pas un protocole.',
  }),
  ar: pack({
    ...shared,
    lead: 'صِل المجس، اختر المنطقة، ثم مرّ به.',
    steps: ['التوصيل', 'المنطقة', 'المرور', 'النتيجة'],
    intro: 'طريقان. مباشرة: مخرج الفيديو في الجهاز عبر بطاقة التقاط إلى منفذ USB في الحاسوب. أو المجس وبرنامجه على جهاز لوحي أو هاتف أو حاسوب، بكابل أو عبر Wi‑Fi.',
    howConnect: 'طريقة التوصيل',
    direct: 'مباشرة إلى الجهاز',
    probeProgram: 'المجس والبرنامج',
    where: 'أين البرنامج',
    machineSteps: [
      'جهاز الموجات، مخرج الفيديو → كابل → بطاقة التقاط HDMI إلى USB → منفذ USB في الحاسوب. مقبس HDMI في الحاسوب لا يستقبل الصورة.',
      'غالبًا يكفي كابل HDMI. منفذ DVI يوصل بكابل DVI إلى HDMI. منفذا DisplayPort وVGA يحتاجان محوّلًا نشطًا إلى HDMI.',
      'بطاقة الالتقاط تأخذ صورة الجهاز وترسلها إلى الحاسوب. ليست محوّلًا يخرج شاشة الحاسوب إلى شاشة أخرى.',
      'اضغط «فتح صورة الجهاز» واسمح بالكاميرا. إذا وُجدت عدة أجهزة، اختر الجهاز الذي تُرى عليه صورة الموجات، ثم «التالي».',
    ],
    openMachine: 'فتح صورة الجهاز',
    cards: 'بطاقات لأجهزة الموجات',
    machineCamera: 'أين تظهر صورة الجهاز',
    onComputer: 'على هذا الحاسوب',
    onPocket: 'على جهاز لوحي أو هاتف',
    howLink: 'كيف يتصل المجس بالبرنامج',
    cable: 'كابل',
    practice: 'بلا جهاز، للتجربة',
    practiceNote: 'صورة تدريب. لا تدخل في ملف المريض.',
    camera: 'أي مجس',
    next: 'التالي',
    guide: {
      computer: {
        cable: [
          'صِل المجس بكابل إلى هذا الحاسوب وافتح برنامج الجهاز.',
          'اضغط «فتح الصورة». اسمح عندما يطلب المتصفح.',
          'إذا وُجدت عدة أجهزة، اختر المجس.',
          'عندما تظهر الصورة، اضغط «التالي».',
        ],
        wifi: [
          'اربط المجس ببرنامج هذا الحاسوب عبر Wi‑Fi وافتح الصورة الحية.',
          'اضغط «إظهار نافذة البرنامج».',
          'في طلب المتصفح اختر نافذة برنامج الجهاز.',
          'عندما تظهر الصورة، اضغط «التالي».',
        ],
      },
      pocket: {
        cable: [
          'صِل المجس بكابل إلى الجهاز اللوحي أو الهاتف. يجب أن تكون الصورة الحية على تلك الشاشة.',
          'اعرض تلك الشاشة على الحاسوب بكابل أو بمشاركة الشاشة.',
          'اضغط «إظهار الشاشة» واختر شاشة الجهاز اللوحي أو الهاتف.',
          'عندما تظهر الصورة، اضغط «التالي».',
        ],
        wifi: [
          'اربط المجس ببرنامج الجهاز اللوحي أو الهاتف عبر Wi‑Fi. يجب أن تكون الصورة الحية على تلك الشاشة.',
          'اعرض تلك الشاشة على الحاسوب بكابل أو بمشاركة الشاشة عبر Wi‑Fi.',
          'اضغط «إظهار الشاشة» واختر شاشة الجهاز اللوحي أو الهاتف.',
          'عندما تظهر الصورة، اضغط «التالي».',
        ],
      },
    },
    practiceSteps: [
      'لا حاجة إلى مجس. هذه صورة تدريب.',
      'اضغط «إظهار صورة التدريب».',
      'لا تدخل في ملف المريض.',
      'عندما تظهر الصورة، اضغط «التالي».',
    ],
    openCable: 'فتح الصورة',
    openWindow: 'إظهار نافذة البرنامج',
    openScreen: 'إظهار الشاشة',
    openPractice: 'إظهار صورة التدريب',
    pictureReady: 'الصورة جاهزة. يمكن اختيار المنطقة.',
    mirror: 'إذا ظهرت هذه الصفحة داخل الصورة، اضغط «فتح من جديد» واختر نافذة برنامج الجهاز. يجب ألا يلتقط المتصفح هذه النافذة.',
    again: 'فتح من جديد',
    areaLead: 'الصورة مفتوحة. اختر العضو واضغط «ابدأ». أثناء المرور تبقى إشارة واحدة فوق الصورة.',
    areaShared: 'نافذة البرنامج متصلة. انظر إليها هناك. هنا اختر العضو واضغط «ابدأ».',
    speak: 'قراءة التوجيه',
    speakOn: 'يُقرأ التوجيه',
    speakHow: 'لسماع هذا السطر، اضغط «قراءة التوجيه».',
    speakLead: '«قراءة التوجيه» ينطق السطر الذي سيظهر أثناء المرور. هذا لا يشغّل الميكروفون.',
    micLead: 'الميكروفون يسجّل الإملاء، بما فيه المقاسات التي تقولها. قبل الاستنتاج يُصاغ بلغة الموجات. أمر «snapshot» يُبقي الإطار.',
    polishing: 'أصوغ الإملاء بلغة الموجات…',
    dictation: 'الإملاء',
    dictationHint: 'هذه الكلمات تذهب إلى الاستنتاج مع الإطارات. الصوت يبقى في هذا اللسان.',
    noAudio: 'لم يُسجَّل صوت في هذا المرور.',
    snapshotHint: 'اضغط «تشغيل الميكروفون». اسمح عندما يطلب المتصفح. ثم قل: snapshot. أو اضغط «إبقاء هذا الإطار».',
    listen: 'تشغيل الميكروفون',
    listenOn: 'أستمع. الإملاء يُسجَّل. قل: snapshot.',
    listenNoCommand: 'الإملاء يُسجَّل. هذا المتصفح لا يسمع «snapshot».',
    listenAsk: 'المتصفح يطلب الميكروفون. اسمح.',
    listenDenied: 'الميكروفون ممنوع. اسمح به في المتصفح أو اضغط «إبقاء هذا الإطار».',
    listenNone: 'هذا المتصفح لا يسمع الأمر. اضغط «إبقاء هذا الإطار».',
    keepFrame: 'إبقاء هذا الإطار',
    kept: 'أُبقي الإطار.',
    pinned: 'الإطارات المبقاة',
    scrub: 'حلقة',
    watchProgram: 'انظر إلى نافذة برنامج الجهاز. لا نكرر الصورة هنا حتى لا تلتقط الصفحة نفسها.',
    own: 'منطقة أخرى',
    ownPlaceholder: 'إذا لم تكن في القائمة',
    start: 'ابدأ',
    stop: 'أوقف',
    live: 'صورة الجهاز',
    writing: 'أختار الإطارات وأكتب الاستنتاج…',
    empty: 'المرور فارغ. ارجع ومرّ بالمجس.',
    reset: 'مسح',
    cine: 'مرور الفحص',
    series: 'إطارات ممثلة',
    conclusion: 'مسودة الاستنتاج',
    protocol: 'بروتوكول طبيب الموجات',
    seen: 'ما يُرى',
    none: 'لا توجد صياغة منفصلة. هذا لا يعني أن كل شيء طبيعي.',
    draft: 'مسودة',
    accepted: 'مقبول',
    rejected: 'مرفوض',
    accept: 'قبول',
    reject: 'رفض',
    wording: 'الصياغة',
    disclaimer: 'إلى أن تقبل الصياغة، هذا ليس تقريرًا.',
  }),
  hi: pack({
    ...shared,
    lead: 'प्रोब जोड़ें, क्षेत्र चुनें, घुमाएँ।',
    steps: ['जोड़ें', 'क्षेत्र', 'स्वीप', 'निष्कर्ष'],
    intro: 'दो रास्ते। सीधे: मशीन का वीडियो आउटपुट कैप्चर कार्ड से कंप्यूटर के USB में। या प्रोब और उसका प्रोग्राम टैबलेट, फ़ोन या कंप्यूटर पर, केबल या Wi‑Fi से।',
    howConnect: 'कैसे जोड़ें',
    direct: 'सीधे मशीन में',
    probeProgram: 'प्रोब और प्रोग्राम',
    where: 'प्रोग्राम कहाँ है',
    machineSteps: [
      'अल्ट्रासाउंड मशीन, वीडियो आउटपुट → केबल → HDMI से USB कैप्चर कार्ड → कंप्यूटर का USB। कंप्यूटर का HDMI सॉकेट चित्र नहीं लेता।',
      'अक्सर HDMI केबल काफी है। DVI के लिए DVI से HDMI केबल। DisplayPort और VGA के लिए HDMI में सक्रिय अडैप्टर।',
      'कैप्चर कार्ड मशीन का चित्र लेता है और कंप्यूटर को देता है। यह वह अडैप्टर नहीं है जो कंप्यूटर की स्क्रीन मॉनिटर पर भेजता है।',
      '«मशीन का चित्र खोलें» दबाएँ और कैमरा अनुमति दें। कई उपकरण हों तो वह चुनें जिसमें मशीन दिखे, फिर «आगे»।',
    ],
    openMachine: 'मशीन का चित्र खोलें',
    cards: 'मशीनों के लिए कार्ड',
    machineCamera: 'मशीन कहाँ दिखती है',
    onComputer: 'इस कंप्यूटर पर',
    onPocket: 'टैबलेट या फ़ोन पर',
    howLink: 'प्रोब प्रोग्राम से कैसे जुड़ा है',
    cable: 'केबल',
    practice: 'बिना मशीन, अभ्यास के लिए',
    practiceNote: 'अभ्यास का चित्र। रोगी के चार्ट में नहीं जाता।',
    camera: 'कौन सा प्रोब',
    next: 'आगे',
    guide: {
      computer: {
        cable: [
          'प्रोब को केबल से इस कंप्यूटर से जोड़ें और मशीन का प्रोग्राम खोलें।',
          '«चित्र खोलें» दबाएँ। ब्राउज़र पूछे तो अनुमति दें।',
          'कई उपकरण हों तो प्रोब चुनें।',
          'चित्र आ जाए तो «आगे» दबाएँ।',
        ],
        wifi: [
          'प्रोब को इस कंप्यूटर के प्रोग्राम से Wi‑Fi पर जोड़ें और जीवित चित्र खोलें।',
          '«प्रोग्राम की विंडो दिखाएँ» दबाएँ।',
          'ब्राउज़र के अनुरोध में मशीन के प्रोग्राम की विंडो चुनें।',
          'चित्र आ जाए तो «आगे» दबाएँ।',
        ],
      },
      pocket: {
        cable: [
          'प्रोब को केबल से टैबलेट या फ़ोन से जोड़ें। उस स्क्रीन पर जीवित चित्र होना चाहिए।',
          'वह स्क्रीन कंप्यूटर पर दिखाएँ: केबल या स्क्रीन शेयर से।',
          '«स्क्रीन दिखाएँ» दबाएँ और टैबलेट या फ़ोन की स्क्रीन चुनें।',
          'चित्र आ जाए तो «आगे» दबाएँ।',
        ],
        wifi: [
          'प्रोब को टैबलेट या फ़ोन के प्रोग्राम से Wi‑Fi पर जोड़ें। उस स्क्रीन पर जीवित चित्र होना चाहिए।',
          'वह स्क्रीन कंप्यूटर पर दिखाएँ: केबल या Wi‑Fi स्क्रीन शेयर से।',
          '«स्क्रीन दिखाएँ» दबाएँ और टैबलेट या फ़ोन की स्क्रीन चुनें।',
          'चित्र आ जाए तो «आगे» दबाएँ।',
        ],
      },
    },
    practiceSteps: [
      'प्रोब की ज़रूरत नहीं। यह अभ्यास का चित्र है।',
      '«अभ्यास का चित्र दिखाएँ» दबाएँ।',
      'यह रोगी के चार्ट में नहीं जाता।',
      'चित्र आ जाए तो «आगे» दबाएँ।',
    ],
    openCable: 'चित्र खोलें',
    openWindow: 'प्रोग्राम की विंडो दिखाएँ',
    openScreen: 'स्क्रीन दिखाएँ',
    openPractice: 'अभ्यास का चित्र दिखाएँ',
    pictureReady: 'चित्र आ गया। क्षेत्र चुन सकते हैं।',
    mirror: 'अगर चित्र के अंदर फिर यह पेज दिखे, «फिर खोलें» दबाएँ और मशीन के प्रोग्राम की विंडो चुनें। यह विंडो ब्राउज़र को नहीं पकड़नी चाहिए।',
    again: 'फिर खोलें',
    areaLead: 'चित्र खुला है। अंग चुनें और «शुरू करें» दबाएँ। पास के दौरान चित्र के ऊपर एक संकेत रहेगा।',
    areaShared: 'प्रोग्राम की विंडो जुड़ी है। उसे वहीं देखें। यहाँ अंग चुनें और «शुरू करें» दबाएँ।',
    speak: 'निर्देश पढ़ें',
    speakOn: 'निर्देश पढ़ा जा रहा है',
    speakHow: 'यह पंक्ति सुनने के लिए «निर्देश पढ़ें» दबाएँ।',
    speakLead: '«निर्देश पढ़ें» वह पंक्ति बोलता है जो पास के दौरान दिखेगी। इससे माइक्रोफ़ोन नहीं चलता।',
    micLead: 'माइक्रोफ़ोन डिक्टेशन लिखता है, आपके कहे आकार सहित। निष्कर्ष से पहले इसे अल्ट्रासाउंड की भाषा में लाया जाता है। आदेश «snapshot» फ़्रेम रखता है।',
    polishing: 'डिक्टेशन को अल्ट्रासाउंड की भाषा में ला रहा हूँ…',
    dictation: 'डिक्टेशन',
    dictationHint: 'ये शब्द फ़्रेमों के साथ निष्कर्ष में जाते हैं। आवाज़ इसी टैब में रहती है।',
    noAudio: 'इस पास पर आवाज़ रिकॉर्ड नहीं हुई।',
    snapshotHint: '«माइक्रोफ़ोन चालू करें» दबाएँ। ब्राउज़र पूछे तो अनुमति दें। फिर कहें: snapshot। या «यह फ़्रेम रखें» दबाएँ।',
    listen: 'माइक्रोफ़ोन चालू करें',
    listenOn: 'सुन रहा हूँ। डिक्टेशन लिख रहा है। कहें: snapshot।',
    listenNoCommand: 'डिक्टेशन लिख रहा है। यह ब्राउज़र «snapshot» नहीं सुनता।',
    listenAsk: 'ब्राउज़र माइक्रोफ़ोन माँग रहा है। अनुमति दें।',
    listenDenied: 'माइक्रोफ़ोन नहीं मिला। ब्राउज़र में अनुमति दें या «यह फ़्रेम रखें» दबाएँ।',
    listenNone: 'यह ब्राउज़र आदेश नहीं सुनता। «यह फ़्रेम रखें» दबाएँ।',
    keepFrame: 'यह फ़्रेम रखें',
    kept: 'फ़्रेम रखा गया।',
    pinned: 'रखे फ़्रेम',
    scrub: 'लूप',
    watchProgram: 'मशीन के प्रोग्राम की विंडो देखें। यहाँ चित्र नहीं दोहराते, ताकि पेज स्वयं को न पकड़े।',
    own: 'दूसरा क्षेत्र',
    ownPlaceholder: 'अगर सूची में नहीं है',
    start: 'शुरू करें',
    stop: 'रोकें',
    live: 'मशीन का चित्र',
    writing: 'फ़्रेम चुन रहा हूँ और निष्कर्ष लिख रहा हूँ…',
    empty: 'पास खाली है। लौटें और प्रोब घुमाएँ।',
    reset: 'रीसेट',
    cine: 'पास की फ़िल्म',
    series: 'प्रतिनिधि फ़्रेम',
    conclusion: 'निष्कर्ष का मसौदा',
    protocol: 'सोनोग्राफर प्रोटोकॉल',
    seen: 'क्या दिखता है',
    none: 'अलग शब्दावली नहीं है। इसका मतलब यह नहीं कि सब सामान्य है।',
    draft: 'मसौदा',
    accepted: 'स्वीकार',
    rejected: 'अस्वीकार',
    accept: 'स्वीकार करें',
    reject: 'अस्वीकार करें',
    wording: 'शब्दावली',
    disclaimer: 'जब तक आप शब्दावली स्वीकार नहीं करते, यह रिपोर्ट नहीं है।',
  }),
  'pt-BR': pack({
    ...shared,
    lead: 'Conecte o transdutor, escolha a região e varra.',
    steps: ['Conectar', 'Região', 'Varredura', 'Resultado'],
    intro: 'Dois caminhos. Direto: a saída de vídeo do aparelho, por uma placa de captura, na USB do computador. Ou o transdutor e o programa dele em um tablet, telefone ou computador, por cabo ou Wi‑Fi.',
    howConnect: 'Como conectar',
    direct: 'Direto no aparelho',
    probeProgram: 'Transdutor e programa',
    where: 'Onde está o programa',
    machineSteps: [
      'Aparelho de ultrassom, saída de vídeo → cabo → placa HDMI para USB → USB do computador. A tomada HDMI do computador não recebe a imagem.',
      'Na maioria basta um cabo HDMI. DVI usa cabo DVI para HDMI. DisplayPort e VGA só com adaptador ativo para HDMI.',
      'A placa de captura pega a imagem do aparelho e a manda ao computador. Não é um adaptador que envia a tela do computador a um monitor.',
      'Pressione «Abrir a imagem do aparelho» e permita a câmera. Se houver vários dispositivos, escolha o que mostra o aparelho e depois «Seguinte».',
    ],
    openMachine: 'Abrir a imagem do aparelho',
    cards: 'Placas para aparelhos',
    machineCamera: 'Onde o aparelho aparece',
    onComputer: 'Neste computador',
    onPocket: 'Em um tablet ou telefone',
    howLink: 'Como o transdutor se liga ao programa',
    cable: 'Cabo',
    practice: 'Sem aparelho, para treino',
    practiceNote: 'Imagem de treino. Não entra no prontuário.',
    camera: 'Qual transdutor',
    next: 'Seguinte',
    guide: {
      computer: {
        cable: [
          'Ligue o transdutor por cabo a este computador e abra o programa do aparelho.',
          'Pressione «Abrir a imagem». Permita quando o navegador pedir.',
          'Se houver vários dispositivos, escolha o transdutor.',
          'Quando a imagem aparecer, pressione «Seguinte».',
        ],
        wifi: [
          'Ligue o transdutor ao programa deste computador por Wi‑Fi e abra a imagem ao vivo.',
          'Pressione «Mostrar a janela do programa».',
          'No pedido do navegador, escolha a janela do programa do aparelho.',
          'Quando a imagem aparecer, pressione «Seguinte».',
        ],
      },
      pocket: {
        cable: [
          'Ligue o transdutor por cabo ao tablet ou telefone. A imagem ao vivo deve estar nessa tela.',
          'Mostre essa tela no computador, por cabo ou por compartilhamento de tela.',
          'Pressione «Mostrar a tela» e escolha a tela do tablet ou do telefone.',
          'Quando a imagem aparecer, pressione «Seguinte».',
        ],
        wifi: [
          'Ligue o transdutor ao programa do tablet ou do telefone por Wi‑Fi. A imagem ao vivo deve estar nessa tela.',
          'Mostre essa tela no computador, por cabo ou por compartilhamento de tela via Wi‑Fi.',
          'Pressione «Mostrar a tela» e escolha a tela do tablet ou do telefone.',
          'Quando a imagem aparecer, pressione «Seguinte».',
        ],
      },
    },
    practiceSteps: [
      'Não é preciso transdutor. Esta é uma imagem de treino.',
      'Pressione «Mostrar a imagem de treino».',
      'Ela não entra no prontuário.',
      'Quando a imagem aparecer, pressione «Seguinte».',
    ],
    openCable: 'Abrir a imagem',
    openWindow: 'Mostrar a janela do programa',
    openScreen: 'Mostrar a tela',
    openPractice: 'Mostrar a imagem de treino',
    pictureReady: 'A imagem está aí. Já pode escolher a região.',
    mirror: 'Se esta página aparecer dentro da imagem, pressione «Abrir de novo» e escolha a janela do programa do aparelho. Esta janela não deve ser compartilhada.',
    again: 'Abrir de novo',
    areaLead: 'A imagem já está aberta. Escolha o órgão e pressione «Começar». Durante a varredura, um aviso fica acima da imagem.',
    areaShared: 'A janela do programa está ligada. Olhe para ela. Aqui, escolha o órgão e pressione «Começar».',
    speak: 'Ler a instrução',
    speakOn: 'A instrução está sendo lida',
    speakHow: 'Para ouvir esta linha, pressione «Ler a instrução».',
    speakLead: '«Ler a instrução» fala a linha que aparecerá durante a varredura. Isso não liga o microfone.',
    micLead: 'O microfone grava o ditado, inclusive os tamanhos que você diz. Antes da conclusão ele passa à linguagem do ultrassom. O comando «snapshot» guarda o quadro.',
    polishing: 'Passando o ditado à linguagem do ultrassom…',
    dictation: 'Ditado',
    dictationHint: 'Estas palavras vão para a conclusão junto com os quadros. O som fica nesta aba.',
    noAudio: 'Nenhuma voz foi gravada nesta varredura.',
    snapshotHint: 'Pressione «Ligar o microfone». Permita quando o navegador pedir. Depois diga: snapshot. Ou pressione «Guardar este quadro».',
    listen: 'Ligar o microfone',
    listenOn: 'Ouvindo. O ditado está sendo gravado. Diga: snapshot.',
    listenNoCommand: 'O ditado está sendo gravado. Este navegador não ouve «snapshot».',
    listenAsk: 'O navegador pede o microfone. Permita.',
    listenDenied: 'O microfone foi bloqueado. Permita-o no navegador ou pressione «Guardar este quadro».',
    listenNone: 'Este navegador não ouve o comando. Pressione «Guardar este quadro».',
    keepFrame: 'Guardar este quadro',
    kept: 'Quadro guardado.',
    pinned: 'Quadros guardados',
    scrub: 'Laço',
    watchProgram: 'Olhe a janela do programa do aparelho. A imagem não se repete aqui, para a página não se capturar.',
    own: 'Outra região',
    ownPlaceholder: 'Se não estiver na lista',
    start: 'Começar',
    stop: 'Parar',
    live: 'Imagem do aparelho',
    writing: 'Escolhendo quadros e escrevendo a conclusão…',
    empty: 'A varredura está vazia. Volte e passe o transdutor.',
    reset: 'Reiniciar',
    cine: 'A varredura',
    series: 'Quadros representativos',
    conclusion: 'Rascunho da conclusão',
    protocol: 'Protocolo do ultrassonografista',
    seen: 'O que se vê',
    none: 'Não há uma redação separada. Isso não significa que tudo está normal.',
    draft: 'Rascunho',
    accepted: 'Aceito',
    rejected: 'Recusado',
    accept: 'Aceitar',
    reject: 'Recusar',
    wording: 'Redação',
    disclaimer: 'Enquanto você não aceitar a redação, isto não é um laudo.',
  }),
  id: pack({
    ...shared,
    lead: 'Hubungkan probe, pilih area, lalu sapukan.',
    steps: ['Hubungkan', 'Area', 'Sapuan', 'Hasil'],
    intro: 'Dua jalur. Langsung: keluaran video mesin lewat kartu tangkap ke USB komputer. Atau probe dan programnya di tablet, ponsel, atau komputer, dengan kabel atau Wi‑Fi.',
    howConnect: 'Cara menghubungkan',
    direct: 'Langsung ke mesin',
    probeProgram: 'Probe dan program',
    where: 'Di mana programnya',
    machineSteps: [
      'Mesin USG, keluaran video → kabel → kartu tangkap HDMI ke USB → USB komputer. Soket HDMI di komputer tidak menerima gambar.',
      'Sering kali kabel HDMI cukup. DVI memakai kabel DVI ke HDMI. DisplayPort dan VGA hanya dengan adaptor aktif ke HDMI.',
      'Kartu tangkap mengambil gambar mesin dan mengirimnya ke komputer. Ini bukan adaptor yang mengirim layar komputer ke monitor.',
      'Tekan «Buka gambar mesin» dan izinkan kamera. Jika ada beberapa perangkat, pilih yang menampilkan mesin, lalu «Lanjut».',
    ],
    openMachine: 'Buka gambar mesin',
    cards: 'Kartu untuk mesin',
    machineCamera: 'Di mana mesin terlihat',
    onComputer: 'Di komputer ini',
    onPocket: 'Di tablet atau ponsel',
    howLink: 'Bagaimana probe terhubung ke program',
    cable: 'Kabel',
    practice: 'Tanpa mesin, untuk latihan',
    practiceNote: 'Gambar latihan. Tidak masuk ke rekam pasien.',
    camera: 'Probe yang mana',
    next: 'Lanjut',
    guide: {
      computer: {
        cable: [
          'Hubungkan probe dengan kabel ke komputer ini dan buka program mesin.',
          'Tekan «Buka gambar». Izinkan saat peramban meminta.',
          'Jika ada beberapa perangkat, pilih probe.',
          'Saat gambar muncul, tekan «Lanjut».',
        ],
        wifi: [
          'Hubungkan probe ke program di komputer ini lewat Wi‑Fi dan buka gambar langsung.',
          'Tekan «Tampilkan jendela program».',
          'Pada permintaan peramban, pilih jendela program mesin.',
          'Saat gambar muncul, tekan «Lanjut».',
        ],
      },
      pocket: {
        cable: [
          'Hubungkan probe dengan kabel ke tablet atau ponsel. Gambar langsung harus ada di layar itu.',
          'Tampilkan layar itu di komputer, dengan kabel atau berbagi layar.',
          'Tekan «Tampilkan layar» dan pilih layar tablet atau ponsel.',
          'Saat gambar muncul, tekan «Lanjut».',
        ],
        wifi: [
          'Hubungkan probe ke program di tablet atau ponsel lewat Wi‑Fi. Gambar langsung harus ada di layar itu.',
          'Tampilkan layar itu di komputer, dengan kabel atau berbagi layar lewat Wi‑Fi.',
          'Tekan «Tampilkan layar» dan pilih layar tablet atau ponsel.',
          'Saat gambar muncul, tekan «Lanjut».',
        ],
      },
    },
    practiceSteps: [
      'Probe tidak diperlukan. Ini gambar latihan.',
      'Tekan «Tampilkan gambar latihan».',
      'Gambar ini tidak masuk ke rekam pasien.',
      'Saat gambar muncul, tekan «Lanjut».',
    ],
    openCable: 'Buka gambar',
    openWindow: 'Tampilkan jendela program',
    openScreen: 'Tampilkan layar',
    openPractice: 'Tampilkan gambar latihan',
    pictureReady: 'Gambar sudah ada. Area bisa dipilih.',
    mirror: 'Jika halaman ini muncul di dalam gambar, tekan «Buka lagi» dan pilih jendela program mesin. Jendela ini tidak boleh ditangkap peramban.',
    again: 'Buka lagi',
    areaLead: 'Gambar sudah terbuka. Pilih organ dan tekan «Mulai». Selama sapuan, satu petunjuk tetap di atas gambar.',
    areaShared: 'Jendela program terhubung. Lihat di sana. Di sini pilih organ dan tekan «Mulai».',
    speak: 'Bacakan petunjuk',
    speakOn: 'Petunjuk dibacakan',
    speakHow: 'Untuk mendengar baris ini, tekan «Bacakan petunjuk».',
    speakLead: '«Bacakan petunjuk» mengucapkan baris yang muncul selama sapuan. Ini tidak menyalakan mikrofon.',
    micLead: 'Mikrofon merekam dikte, termasuk ukuran yang Anda sebut. Sebelum kesimpulan, dikte disusun ke bahasa USG. Perintah «snapshot» menyimpan bingkai.',
    polishing: 'Menyusun dikte ke bahasa USG…',
    dictation: 'Dikte',
    dictationHint: 'Kata-kata ini masuk ke kesimpulan bersama bingkai. Suara tetap di tab ini.',
    noAudio: 'Suara tidak terekam pada sapuan ini.',
    snapshotHint: 'Tekan «Nyalakan mikrofon». Izinkan saat peramban meminta. Lalu ucapkan: snapshot. Atau tekan «Simpan bingkai ini».',
    listen: 'Nyalakan mikrofon',
    listenOn: 'Mendengarkan. Dikte sedang direkam. Ucapkan: snapshot.',
    listenNoCommand: 'Dikte sedang direkam. Peramban ini tidak mendengar «snapshot».',
    listenAsk: 'Peramban meminta mikrofon. Izinkan.',
    listenDenied: 'Mikrofon ditolak. Izinkan di peramban, atau tekan «Simpan bingkai ini».',
    listenNone: 'Peramban ini tidak mendengar perintah. Tekan «Simpan bingkai ini».',
    keepFrame: 'Simpan bingkai ini',
    kept: 'Bingkai disimpan.',
    pinned: 'Bingkai tersimpan',
    scrub: 'Putaran',
    watchProgram: 'Lihat jendela program mesin. Gambar tidak diulang di sini agar halaman tidak menangkap dirinya sendiri.',
    own: 'Area lain',
    ownPlaceholder: 'Jika tidak ada di daftar',
    start: 'Mulai',
    stop: 'Berhenti',
    live: 'Gambar dari mesin',
    writing: 'Memilih bingkai dan menulis kesimpulan…',
    empty: 'Sapuan kosong. Kembali dan sapukan probe.',
    reset: 'Atur ulang',
    cine: 'Sapuan',
    series: 'Bingkai wakil',
    conclusion: 'Draf kesimpulan',
    protocol: 'Protokol dokter USG',
    seen: 'Yang terlihat',
    none: 'Tidak ada rumusan terpisah. Itu tidak berarti semuanya normal.',
    draft: 'Draf',
    accepted: 'Diterima',
    rejected: 'Ditolak',
    accept: 'Terima',
    reject: 'Tolak',
    wording: 'Rumusan',
    disclaimer: 'Sebelum rumusan diterima, ini bukan laporan.',
  }),
  ms: pack({
    ...shared,
    lead: 'Sambungkan prob, pilih kawasan, kemudian sapu.',
    steps: ['Sambung', 'Kawasan', 'Sapuan', 'Hasil'],
    intro: 'Dua laluan. Terus: keluaran video mesin melalui kad tangkap ke USB komputer. Atau prob dan programnya pada tablet, telefon atau komputer, dengan kabel atau Wi‑Fi.',
    howConnect: 'Cara menyambung',
    direct: 'Terus ke mesin',
    probeProgram: 'Prob dan program',
    where: 'Di mana program',
    machineSteps: [
      'Mesin ultrasound, keluaran video → kabel → kad tangkap HDMI ke USB → USB komputer. Soket HDMI pada komputer tidak menerima gambar.',
      'Selalunya kabel HDMI memadai. DVI menggunakan kabel DVI ke HDMI. DisplayPort dan VGA hanya dengan penyesuai aktif ke HDMI.',
      'Kad tangkap mengambil gambar mesin dan menghantarnya ke komputer. Ia bukan penyesuai yang menghantar skrin komputer ke monitor.',
      'Tekan «Buka gambar mesin» dan benarkan kamera. Jika ada beberapa peranti, pilih yang menunjukkan mesin, kemudian «Seterusnya».',
    ],
    openMachine: 'Buka gambar mesin',
    cards: 'Kad untuk mesin',
    machineCamera: 'Di mana mesin kelihatan',
    onComputer: 'Pada komputer ini',
    onPocket: 'Pada tablet atau telefon',
    howLink: 'Bagaimana prob dihubungkan ke program',
    cable: 'Kabel',
    practice: 'Tanpa mesin, untuk latihan',
    practiceNote: 'Gambar latihan. Tidak masuk ke rekod pesakit.',
    camera: 'Prob yang mana',
    next: 'Seterusnya',
    guide: {
      computer: {
        cable: [
          'Sambungkan prob dengan kabel ke komputer ini dan buka program mesin.',
          'Tekan «Buka gambar». Benarkan apabila pelayar meminta.',
          'Jika ada beberapa peranti, pilih prob.',
          'Apabila gambar muncul, tekan «Seterusnya».',
        ],
        wifi: [
          'Hubungkan prob ke program pada komputer ini melalui Wi‑Fi dan buka gambar langsung.',
          'Tekan «Tunjuk tetingkap program».',
          'Pada permintaan pelayar, pilih tetingkap program mesin.',
          'Apabila gambar muncul, tekan «Seterusnya».',
        ],
      },
      pocket: {
        cable: [
          'Sambungkan prob dengan kabel ke tablet atau telefon. Gambar langsung mesti ada pada skrin itu.',
          'Tunjukkan skrin itu pada komputer, dengan kabel atau perkongsian skrin.',
          'Tekan «Tunjuk skrin» dan pilih skrin tablet atau telefon.',
          'Apabila gambar muncul, tekan «Seterusnya».',
        ],
        wifi: [
          'Hubungkan prob ke program pada tablet atau telefon melalui Wi‑Fi. Gambar langsung mesti ada pada skrin itu.',
          'Tunjukkan skrin itu pada komputer, dengan kabel atau perkongsian skrin melalui Wi‑Fi.',
          'Tekan «Tunjuk skrin» dan pilih skrin tablet atau telefon.',
          'Apabila gambar muncul, tekan «Seterusnya».',
        ],
      },
    },
    practiceSteps: [
      'Prob tidak diperlukan. Ini gambar latihan.',
      'Tekan «Tunjuk gambar latihan».',
      'Ia tidak masuk ke rekod pesakit.',
      'Apabila gambar muncul, tekan «Seterusnya».',
    ],
    openCable: 'Buka gambar',
    openWindow: 'Tunjuk tetingkap program',
    openScreen: 'Tunjuk skrin',
    openPractice: 'Tunjuk gambar latihan',
    pictureReady: 'Gambar sudah ada. Kawasan boleh dipilih.',
    mirror: 'Jika halaman ini muncul di dalam gambar, tekan «Buka semula» dan pilih tetingkap program mesin. Tetingkap ini tidak patut ditangkap pelayar.',
    again: 'Buka semula',
    areaLead: 'Gambar sudah terbuka. Pilih organ dan tekan «Mula». Semasa sapuan, satu petunjuk kekal di atas gambar.',
    areaShared: 'Tetingkap program disambungkan. Lihat di sana. Di sini pilih organ dan tekan «Mula».',
    speak: 'Baca arahan',
    speakOn: 'Arahan sedang dibaca',
    speakHow: 'Untuk mendengar baris ini, tekan «Baca arahan».',
    speakLead: '«Baca arahan» menyebut baris yang akan muncul semasa sapuan. Ini tidak menghidupkan mikrofon.',
    micLead: 'Mikrofon merakam imlak, termasuk saiz yang anda sebut. Sebelum kesimpulan, imlak disusun ke bahasa ultrasound. Arahan «snapshot» menyimpan bingkai.',
    polishing: 'Menyusun imlak ke bahasa ultrasound…',
    dictation: 'Imlak',
    dictationHint: 'Perkataan ini masuk ke kesimpulan bersama bingkai. Bunyi kekal dalam tab ini.',
    noAudio: 'Suara tidak dirakam pada sapuan ini.',
    snapshotHint: 'Tekan «Hidupkan mikrofon». Benarkan apabila pelayar meminta. Kemudian sebut: snapshot. Atau tekan «Simpan bingkai ini».',
    listen: 'Hidupkan mikrofon',
    listenOn: 'Mendengar. Imlak sedang dirakam. Sebut: snapshot.',
    listenNoCommand: 'Imlak sedang dirakam. Pelayar ini tidak mendengar «snapshot».',
    listenAsk: 'Pelayar meminta mikrofon. Benarkan.',
    listenDenied: 'Mikrofon disekat. Benarkan dalam pelayar, atau tekan «Simpan bingkai ini».',
    listenNone: 'Pelayar ini tidak mendengar arahan. Tekan «Simpan bingkai ini».',
    keepFrame: 'Simpan bingkai ini',
    kept: 'Bingkai disimpan.',
    pinned: 'Bingkai tersimpan',
    scrub: 'Gelung',
    watchProgram: 'Lihat tetingkap program mesin. Gambar tidak diulang di sini supaya halaman tidak menangkap dirinya.',
    own: 'Kawasan lain',
    ownPlaceholder: 'Jika tiada dalam senarai',
    start: 'Mula',
    stop: 'Henti',
    live: 'Gambar dari mesin',
    writing: 'Memilih bingkai dan menulis kesimpulan…',
    empty: 'Sapuan kosong. Kembali dan sapu prob.',
    reset: 'Set semula',
    cine: 'Sapuan',
    series: 'Bingkai wakil',
    conclusion: 'Draf kesimpulan',
    protocol: 'Protokol doktor ultrasound',
    seen: 'Apa yang kelihatan',
    none: 'Tiada rumusan berasingan. Itu tidak bermakna semuanya normal.',
    draft: 'Draf',
    accepted: 'Diterima',
    rejected: 'Ditolak',
    accept: 'Terima',
    reject: 'Tolak',
    wording: 'Rumusan',
    disclaimer: 'Selagi rumusan belum diterima, ini bukan laporan.',
  }),
  tr: pack({
    ...shared,
    lead: 'Probu bağlayın, bölgeyi seçin, gezdirin.',
    steps: ['Bağla', 'Bölge', 'Geçiş', 'Sonuç'],
    intro: 'İki yol. Doğrudan: cihazın video çıkışı, yakalama kartı üzerinden bilgisayarın USB girişine. Ya da prob ve programı tablette, telefonda veya bilgisayarda, kablo ya da Wi‑Fi ile.',
    howConnect: 'Nasıl bağlanır',
    direct: 'Doğrudan cihaza',
    probeProgram: 'Prob ve program',
    where: 'Program nerede',
    machineSteps: [
      'Ultrason cihazı, video çıkışı → kablo → HDMI’den USB’ye yakalama kartı → bilgisayarın USB’si. Bilgisayardaki HDMI girişi görüntüyü almaz.',
      'Çoğu zaman HDMI kablosu yeter. DVI, DVI’den HDMI’ye kablo kullanır. DisplayPort ve VGA yalnızca HDMI’ye etkin dönüştürücü ile olur.',
      'Yakalama kartı cihazın görüntüsünü alır ve bilgisayara verir. Bilgisayar ekranını monitöre çıkaran bir dönüştürücü değildir.',
      '«Cihaz görüntüsünü aç»a basın ve kameraya izin verin. Birden çok aygıt varsa cihazın göründüğünü seçin, sonra «İleri».',
    ],
    openMachine: 'Cihaz görüntüsünü aç',
    cards: 'Cihazlar için kartlar',
    machineCamera: 'Cihaz nerede görünüyor',
    onComputer: 'Bu bilgisayarda',
    onPocket: 'Tablette veya telefonda',
    howLink: 'Prob programa nasıl bağlı',
    cable: 'Kablo',
    practice: 'Cihaz yok, deneme için',
    practiceNote: 'Deneme görüntüsü. Hasta dosyasına girmez.',
    camera: 'Hangi prob',
    next: 'İleri',
    guide: {
      computer: {
        cable: [
          'Probu kabloyla bu bilgisayara bağlayın ve cihaz programını açın.',
          '«Görüntüyü aç»a basın. Tarayıcı sorunca izin verin.',
          'Birden çok aygıt varsa probu seçin.',
          'Görüntü gelince «İleri»ye basın.',
        ],
        wifi: [
          'Probu bu bilgisayardaki programa Wi‑Fi ile bağlayın ve canlı görüntüyü açın.',
          '«Program penceresini göster»e basın.',
          'Tarayıcının isteğinde cihaz programının penceresini seçin.',
          'Görüntü gelince «İleri»ye basın.',
        ],
      },
      pocket: {
        cable: [
          'Probu kabloyla tablete veya telefona bağlayın. Canlı görüntü o ekranda olmalıdır.',
          'O ekranı bilgisayarda gösterin: kabloyla veya ekran paylaşımıyla.',
          '«Ekranı göster»e basın ve tablet ya da telefon ekranını seçin.',
          'Görüntü gelince «İleri»ye basın.',
        ],
        wifi: [
          'Probu tabletteki veya telefondaki programa Wi‑Fi ile bağlayın. Canlı görüntü o ekranda olmalıdır.',
          'O ekranı bilgisayarda gösterin: kabloyla veya Wi‑Fi ekran paylaşımıyla.',
          '«Ekranı göster»e basın ve tablet ya da telefon ekranını seçin.',
          'Görüntü gelince «İleri»ye basın.',
        ],
      },
    },
    practiceSteps: [
      'Prob gerekmez. Bu bir deneme görüntüsüdür.',
      '«Deneme görüntüsünü göster»e basın.',
      'Hasta dosyasına girmez.',
      'Görüntü gelince «İleri»ye basın.',
    ],
    openCable: 'Görüntüyü aç',
    openWindow: 'Program penceresini göster',
    openScreen: 'Ekranı göster',
    openPractice: 'Deneme görüntüsünü göster',
    pictureReady: 'Görüntü geldi. Bölge seçilebilir.',
    mirror: 'Görüntünün içinde yine bu sayfa çıkarsa «Yeniden aç»a basın ve cihaz programının penceresini seçin. Bu pencere paylaşılmamalıdır.',
    again: 'Yeniden aç',
    areaLead: 'Görüntü açık. Organı seçin ve «Başla»ya basın. Geçiş sırasında görüntünün üstünde bir ipucu kalır.',
    areaShared: 'Program penceresi bağlı. Oraya bakın. Burada organı seçin ve «Başla»ya basın.',
    speak: 'Yönergeyi oku',
    speakOn: 'Yönerge okunuyor',
    speakHow: 'Bu satırı duymak için «Yönergeyi oku»ya basın.',
    speakLead: '«Yönergeyi oku», geçiş sırasında görünecek satırı söyler. Mikrofonu açmaz.',
    micLead: 'Mikrofon dikteyi, söylediğiniz boyutlarla birlikte kaydeder. Sonuçtan önce ultrason diline getirilir. «snapshot» komutu kareyi tutar.',
    polishing: 'Dikte ultrason diline getiriliyor…',
    dictation: 'Dikte',
    dictationHint: 'Bu sözler karelerle birlikte sonuca gider. Ses bu sekmede kalır.',
    noAudio: 'Bu geçişte ses kaydedilmedi.',
    snapshotHint: '«Mikrofonu aç»a basın. Tarayıcı sorunca izin verin. Sonra deyin: snapshot. Ya da «Bu kareyi tut»a basın.',
    listen: 'Mikrofonu aç',
    listenOn: 'Dinliyorum. Dikte kaydediliyor. Deyin: snapshot.',
    listenNoCommand: 'Dikte kaydediliyor. Bu tarayıcı «snapshot» duymaz.',
    listenAsk: 'Tarayıcı mikrofon istiyor. İzin verin.',
    listenDenied: 'Mikrofon engellendi. Tarayıcıda izin verin veya «Bu kareyi tut»a basın.',
    listenNone: 'Bu tarayıcı komutu duymaz. «Bu kareyi tut»a basın.',
    keepFrame: 'Bu kareyi tut',
    kept: 'Kare tutuldu.',
    pinned: 'Tutulan kareler',
    scrub: 'Döngü',
    watchProgram: 'Cihaz programının penceresine bakın. Sayfa kendini yakalamasın diye görüntü burada yinelenmez.',
    own: 'Başka bölge',
    ownPlaceholder: 'Listede yoksa',
    start: 'Başla',
    stop: 'Durdur',
    live: 'Cihazdan görüntü',
    writing: 'Kareler seçiliyor ve sonuç yazılıyor…',
    empty: 'Geçiş boş. Geri dönün ve probu gezdirin.',
    reset: 'Sıfırla',
    cine: 'Geçiş',
    series: 'Temsilî kareler',
    conclusion: 'Sonuç taslağı',
    protocol: 'Ultrason protokolü',
    seen: 'Ne görülüyor',
    none: 'Ayrı bir ifade yok. Bu, her şeyin normal olduğu anlamına gelmez.',
    draft: 'Taslak',
    accepted: 'Kabul',
    rejected: 'Red',
    accept: 'Kabul et',
    reject: 'Reddet',
    wording: 'İfade',
    disclaimer: 'İfadeyi kabul edene kadar bu bir rapor değildir.',
  }),
  'zh-CN': pack({
    ...shared,
    lead: '接上探头，选择区域，然后扫查。',
    steps: ['连接', '区域', '扫查', '结论'],
    intro: '两条路径。直接：超声仪的视频输出经采集卡进入电脑 USB。或者探头及其程序在平板、手机或电脑上，用线缆或 Wi‑Fi。',
    howConnect: '如何连接',
    direct: '直接接入超声仪',
    probeProgram: '探头和程序',
    where: '程序在哪里',
    machineSteps: [
      '超声仪视频输出 → 线缆 → HDMI 转 USB 采集卡 → 电脑 USB。电脑上的 HDMI 接口不接收这路图像。',
      '多数机器用 HDMI 线即可。DVI 用 DVI 转 HDMI 线。DisplayPort 和 VGA 必须用有源转换器转到 HDMI。',
      '采集卡取得超声仪的图像并送入电脑。它不是把电脑画面输出到显示器的转换器。',
      '按「打开仪器图像」并允许摄像头。若有多个设备，选择能看到超声仪的那个，然后按「下一步」。',
    ],
    openMachine: '打开仪器图像',
    cards: '仪器用采集卡',
    machineCamera: '仪器画面在哪里',
    onComputer: '在这台电脑上',
    onPocket: '在平板或手机上',
    howLink: '探头如何连到程序',
    cable: '线缆',
    practice: '没有仪器，用于练习',
    practiceNote: '练习图像。不会进入患者病历。',
    camera: '哪一个探头',
    next: '下一步',
    guide: {
      computer: {
        cable: [
          '用线缆把探头接到这台电脑，并打开仪器程序。',
          '按「打开图像」。浏览器询问时请允许。',
          '若有多个设备，选择探头。',
          '图像出现后，按「下一步」。',
        ],
        wifi: [
          '通过 Wi‑Fi 把探头连到这台电脑上的程序，并打开实时图像。',
          '按「显示程序窗口」。',
          '在浏览器提示中选择仪器程序的窗口。',
          '图像出现后，按「下一步」。',
        ],
      },
      pocket: {
        cable: [
          '用线缆把探头接到平板或手机。那块屏幕上应有实时图像。',
          '把那块屏幕显示到电脑上：用线缆或屏幕共享。',
          '按「显示屏幕」，选择平板或手机的屏幕。',
          '图像出现后，按「下一步」。',
        ],
        wifi: [
          '通过 Wi‑Fi 把探头连到平板或手机上的程序。那块屏幕上应有实时图像。',
          '把那块屏幕显示到电脑上：用线缆或 Wi‑Fi 屏幕共享。',
          '按「显示屏幕」，选择平板或手机的屏幕。',
          '图像出现后，按「下一步」。',
        ],
      },
    },
    practiceSteps: [
      '不需要探头。这是练习图像。',
      '按「显示练习图像」。',
      '它不会进入患者病历。',
      '图像出现后，按「下一步」。',
    ],
    openCable: '打开图像',
    openWindow: '显示程序窗口',
    openScreen: '显示屏幕',
    openPractice: '显示练习图像',
    pictureReady: '图像已在。可以选择区域。',
    mirror: '如果图像里面又出现这一页，按「重新打开」，并选择仪器程序的窗口。浏览器不应采集这个窗口。',
    again: '重新打开',
    areaLead: '图像已经打开。选择器官并按「开始」。扫查时，图像上方会保留一条提示。',
    areaShared: '程序窗口已连接。请看那个窗口。在这里选择器官并按「开始」。',
    speak: '朗读提示',
    speakOn: '正在朗读提示',
    speakHow: '要听到这一行，请按「朗读提示」。',
    speakLead: '「朗读提示」会说出扫查时出现的那一行。这不会打开麦克风。',
    micLead: '麦克风记录口述，包括您说出的尺寸。写结论前会整理成超声用语。口令「snapshot」保留这一帧。',
    polishing: '正在把口述整理成超声用语…',
    dictation: '口述',
    dictationHint: '这些词和画面一起进入结论。声音留在这个标签页。',
    noAudio: '这一次扫查没有录到声音。',
    snapshotHint: '按「打开麦克风」。浏览器询问时请允许。然后说：snapshot。或者按「保留这一帧」。',
    listen: '打开麦克风',
    listenOn: '正在听。口述正在记录。请说：snapshot。',
    listenNoCommand: '口述正在记录。这个浏览器听不到「snapshot」。',
    listenAsk: '浏览器正在请求麦克风。请允许。',
    listenDenied: '麦克风被拒绝。请在浏览器中允许，或按「保留这一帧」。',
    listenNone: '这个浏览器听不到口令。请按「保留这一帧」。',
    keepFrame: '保留这一帧',
    kept: '这一帧已保留。',
    pinned: '已保留的帧',
    scrub: '回放',
    watchProgram: '请看仪器程序的窗口。这里不重复图像，以免这一页采集到自己。',
    own: '其他区域',
    ownPlaceholder: '如果列表里没有',
    start: '开始',
    stop: '停止',
    live: '仪器图像',
    writing: '正在挑选画面并写结论…',
    empty: '扫查是空的。请返回并用探头扫过。',
    reset: '重置',
    cine: '扫查过程',
    series: '代表性画面',
    conclusion: '结论草稿',
    protocol: '超声医师协议',
    seen: '所见',
    none: '没有单独的表述。这并不表示一切正常。',
    draft: '草稿',
    accepted: '已接受',
    rejected: '已拒绝',
    accept: '接受',
    reject: '拒绝',
    wording: '表述',
    disclaimer: '在您接受表述之前，这不是报告。',
  }),
}
